# @generated by scripts/highlevelstubgen.py; DO NOT EDIT.
from __future__ import annotations

from . import models as models
from .beacon import InteractiveBeacon as InteractiveBeacon
from .client import SliverClient as SliverClient
from .config import SliverClientConfig as SliverClientConfig
from .config import SliverWireGuardConfig as SliverWireGuardConfig
from .models import ProtobufEnum as ProtobufEnum
from .models import ProtobufModel as ProtobufModel
from .models import get_pydantic_model as get_pydantic_model
from .session import InteractiveSession as InteractiveSession

__version__: str
