# @generated by scripts/highlevelstubgen.py; DO NOT EDIT.

from __future__ import annotations

import grpc

from . import models
from .interactive import BaseInteractiveCommands

class BaseBeacon:
    timeout: int

    def __init__(self, beacon: models.clientpb.Beacon, channel: grpc.aio.Channel, timeout: int=60) -> None:
        ...

    async def close(self) -> None:
        ...

    @property
    def beacon(self) -> models.clientpb.Beacon:
        ...

    @property
    def beacon_id(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def hostname(self) -> str:
        ...

    @property
    def uuid(self) -> str:
        ...

    @property
    def username(self) -> str:
        ...

    @property
    def uid(self) -> str:
        ...

    @property
    def gid(self) -> str:
        ...

    @property
    def os(self) -> str:
        ...

    @property
    def arch(self) -> str:
        ...

    @property
    def transport(self) -> str:
        ...

    @property
    def remote_address(self) -> str:
        ...

    @property
    def pid(self) -> int:
        ...

    @property
    def filename(self) -> str:
        ...

    @property
    def last_checkin(self) -> int:
        ...

    @property
    def active_c2(self) -> str:
        ...

    @property
    def version(self) -> str:
        ...

    @property
    def reconnect_interval(self) -> int:
        ...

class InteractiveBeacon(BaseBeacon, BaseInteractiveCommands):
    ...
