# @generated by scripts/highlevelstubgen.py; DO NOT EDIT.

from __future__ import annotations

import os
from collections.abc import AsyncGenerator, Collection
from contextlib import AbstractAsyncContextManager
from datetime import timedelta

import grpc

from . import models
from ._rpc import PydanticSliverRPCStub
from .beacon import InteractiveBeacon
from .config import SliverClientConfig
from .domain import GeneratedImplant, ImplantSpec, Inventory
from .enums import EventType
from .session import InteractiveSession

KB: int
MB: int
GB: int
TIMEOUT: int

class BaseClient:
    config: SliverClientConfig

    MAX_MESSAGE_LENGTH: int

    KEEP_ALIVE_TIMEOUT: int

    CERT_COMMON_NAME: str

    def __init__(self, config: SliverClientConfig) -> None:
        ...

    def is_connected(self) -> bool:
        ...

    async def __aenter__(self) -> BaseClient:
        ...

    async def __aexit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, traceback: object | None) -> None:
        ...

    async def connect(self, timeout: int=TIMEOUT) -> models.clientpb.Version:
        ...

    async def close(self) -> None:
        ...

    async def aclose(self) -> None:
        ...

    @property
    def target(self) -> str:
        ...

    @property
    def credentials(self) -> grpc.ChannelCredentials:
        ...

    @property
    def options(self) -> list[tuple[str, int | str]]:
        ...

    @property
    def rpc(self) -> PydanticSliverRPCStub:
        ...

    @property
    def pydantic_stub(self) -> PydanticSliverRPCStub:
        ...

class SliverClient(BaseClient):
    @classmethod
    def from_config_file(cls, filepath: os.PathLike[str] | str | None=None) -> SliverClient:
        ...

    async def __aenter__(self) -> SliverClient:
        ...

    async def connect(self, timeout: int=TIMEOUT) -> models.clientpb.Version:
        ...

    async def interact_session(self, session_id: str, timeout: int=TIMEOUT) -> InteractiveSession | None:
        ...

    async def interact_beacon(self, beacon_id: str, timeout: int=TIMEOUT) -> InteractiveBeacon | None:
        ...

    async def use_session(self, session_id: str, timeout: int=TIMEOUT) -> InteractiveSession:
        ...

    async def use_beacon(self, beacon_id: str, timeout: int=TIMEOUT) -> InteractiveBeacon:
        ...

    async def use(self, target: models.clientpb.Session | models.clientpb.Beacon, timeout: int=TIMEOUT) -> InteractiveSession | InteractiveBeacon:
        ...

    async def session_by_id(self, session_id: str, timeout: int=TIMEOUT) -> models.clientpb.Session | None:
        ...

    async def beacon_by_id(self, beacon_id: str, timeout: int=TIMEOUT) -> models.clientpb.Beacon | None:
        ...

    async def find_session(self, session_id: str, timeout: int=TIMEOUT) -> models.clientpb.Session | None:
        ...

    async def get_session(self, session_id: str, timeout: int=TIMEOUT) -> models.clientpb.Session:
        ...

    async def find_beacon(self, beacon_id: str, timeout: int=TIMEOUT) -> models.clientpb.Beacon | None:
        ...

    async def get_beacon(self, beacon_id: str, timeout: int=TIMEOUT) -> models.clientpb.Beacon:
        ...

    def events(self, event_types: EventType | str | Collection[EventType | str] | None=None) -> AsyncGenerator[models.clientpb.Event]:
        ...

    def on(self, event_types: EventType | str | Collection[EventType | str]) -> AsyncGenerator[models.clientpb.Event]:
        ...

    async def collect_events(self, *event_types: EventType | str, limit: int=1, timeout: float | None=None) -> list[models.clientpb.Event]:
        ...

    async def version(self, timeout: int=TIMEOUT) -> models.clientpb.Version:
        ...

    async def operators(self, timeout: int=TIMEOUT) -> list[models.clientpb.Operator]:
        ...

    async def inventory(self, timeout: int=TIMEOUT) -> Inventory:
        ...

    async def sessions(self, timeout: int=TIMEOUT) -> list[models.clientpb.Session]:
        ...

    async def rename_session(self, session_id: str, name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def kill_session(self, session_id: str, force: bool=False, timeout: int=TIMEOUT) -> None:
        ...

    async def beacons(self, timeout: int=TIMEOUT) -> list[models.clientpb.Beacon]:
        ...

    async def rename_beacon(self, beacon_id: str, name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def kill_beacon(self, beacon_id: str, force: bool=False, timeout: int=TIMEOUT) -> None:
        ...

    async def rm_beacon(self, beacon_id: str, timeout: int=TIMEOUT) -> None:
        ...

    async def beacons_rm(self, beacon_id: str, timeout: int=TIMEOUT) -> None:
        ...

    async def beacon_tasks(self, beacon_id: str, timeout: int=TIMEOUT) -> list[models.clientpb.BeaconTask]:
        ...

    async def beacon_task_content(self, task_id: str, timeout: int=TIMEOUT) -> models.clientpb.BeaconTask:
        ...

    async def tasks(self, beacon_id: str, timeout: int=TIMEOUT) -> list[models.clientpb.BeaconTask]:
        ...

    async def tasks_fetch(self, task_id: str, timeout: int=TIMEOUT) -> models.clientpb.BeaconTask:
        ...

    async def fetch_task(self, task_id: str, timeout: int=TIMEOUT) -> models.clientpb.BeaconTask:
        ...

    async def cancel_task(self, task_id: str, timeout: int=TIMEOUT) -> models.clientpb.BeaconTask:
        ...

    async def tasks_cancel(self, task_id: str, timeout: int=TIMEOUT) -> models.clientpb.BeaconTask:
        ...

    async def jobs(self, timeout: int=TIMEOUT) -> list[models.clientpb.Job]:
        ...

    async def job_by_id(self, job_id: int, timeout: int=TIMEOUT) -> models.clientpb.Job | None:
        ...

    async def job_by_port(self, job_port: int, timeout: int=TIMEOUT) -> models.clientpb.Job | None:
        ...

    async def find_job(self, job_id: int, timeout: int=TIMEOUT) -> models.clientpb.Job | None:
        ...

    async def get_job(self, job_id: int, timeout: int=TIMEOUT) -> models.clientpb.Job:
        ...

    async def kill_job(self, job_id: int, timeout: int=TIMEOUT) -> models.clientpb.KillJob:
        ...

    async def mtls(self, *, host: str='0.0.0.0', port: int=8888, timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    async def wg(self, *, tun_ip: str | None=None, host: str='0.0.0.0', port: int=53, n_port: int=8888, key_port: int=1337, timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    async def dns(self, domains: list[str], *, host: str='0.0.0.0', port: int=53, canaries: bool=True, enforce_otp: bool=True, timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    async def http(self, *, host: str='0.0.0.0', port: int=80, website: str='', domain: str='', enforce_otp: bool=True, long_poll_timeout: timedelta | int=timedelta(seconds=1), long_poll_jitter: timedelta | int=timedelta(seconds=2), timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    async def https(self, *, host: str='0.0.0.0', port: int=443, website: str='', domain: str='', cert: bytes=b'', key: bytes=b'', acme: bool=False, enforce_otp: bool=True, randomize_jarm: bool=True, long_poll_timeout: timedelta | int=timedelta(seconds=1), long_poll_jitter: timedelta | int=timedelta(seconds=2), timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    def temporary_mtls(self, *, host: str='0.0.0.0', port: int=8888, timeout: int=TIMEOUT) -> AbstractAsyncContextManager[models.clientpb.ListenerJob]:
        ...

    async def start_mtls_listener(self, host: str='0.0.0.0', port: int=8888, timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    async def start_wg_listener(self, tun_ip: str | None=None, host: str='0.0.0.0', port: int=53, n_port: int=8888, key_port: int=1337, timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    async def start_dns_listener(self, domains: list[str], host: str='0.0.0.0', port: int=53, canaries: bool=True, enforce_otp: bool=True, timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    async def start_http_listener(self, host: str='0.0.0.0', port: int=80, website: str='', domain: str='', enforce_otp: bool=True, long_poll_timeout: timedelta | int=timedelta(seconds=1), long_poll_jitter: timedelta | int=timedelta(seconds=2), timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    async def start_https_listener(self, host: str='0.0.0.0', port: int=443, website: str='', domain: str='', cert: bytes=b'', key: bytes=b'', acme: bool=False, enforce_otp: bool=True, randomize_jarm: bool=True, long_poll_timeout: timedelta | int=timedelta(seconds=1), long_poll_jitter: timedelta | int=timedelta(seconds=2), timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    async def start_tcp_stager_listener(self, host: str, port: int, data: bytes, timeout: int=TIMEOUT) -> models.clientpb.StagerListener:
        ...

    async def stage_listener(self, host: str, port: int, data: bytes, timeout: int=TIMEOUT) -> models.clientpb.StagerListener:
        ...

    async def generate_implant(self, config: models.clientpb.ImplantConfig, timeout: int=360) -> models.clientpb.Generate:
        ...

    async def generate(self, spec: ImplantSpec, *, name: str='', timeout: int=360, base_config: models.clientpb.ImplantConfig | None=None) -> GeneratedImplant:
        ...

    async def generate_stage(self, request: models.clientpb.GenerateStageReq, timeout: int=360) -> models.clientpb.Generate:
        ...

    async def profiles_stage(self, request: models.clientpb.GenerateStageReq, timeout: int=360) -> GeneratedImplant:
        ...

    async def regenerate_implant(self, implant_name: str, timeout: int=TIMEOUT) -> models.clientpb.Generate:
        ...

    async def regenerate(self, implant_name: str, timeout: int=TIMEOUT) -> GeneratedImplant:
        ...

    async def implant_builds(self, timeout: int=TIMEOUT) -> dict[str, models.clientpb.ImplantConfig]:
        ...

    async def implants(self, timeout: int=TIMEOUT) -> dict[str, models.clientpb.ImplantConfig]:
        ...

    async def delete_implant_build(self, implant_name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def rm_implant(self, implant_name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def implants_rm(self, implant_name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def canaries(self, timeout: int=TIMEOUT) -> list[models.clientpb.DNSCanary]:
        ...

    async def generate_wg_client_config(self, timeout: int=TIMEOUT) -> models.clientpb.WGClientConfig:
        ...

    async def wg_config(self, timeout: int=TIMEOUT) -> models.clientpb.WGClientConfig:
        ...

    async def generate_wg_ip(self, timeout: int=TIMEOUT) -> models.clientpb.UniqueWGIP:
        ...

    async def implant_profiles(self, timeout: int=TIMEOUT) -> list[models.clientpb.ImplantProfile]:
        ...

    async def profiles(self, timeout: int=TIMEOUT) -> list[models.clientpb.ImplantProfile]:
        ...

    async def profiles_generate(self, profile_name: str, *, name: str='', timeout: int=360) -> GeneratedImplant:
        ...

    async def delete_implant_profile(self, profile_name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def rm_profile(self, profile_name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def profiles_rm(self, profile_name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def save_implant_profile(self, profile: models.clientpb.ImplantProfile, timeout: int=TIMEOUT) -> models.clientpb.ImplantProfile:
        ...

    async def new_profile(self, profile: models.clientpb.ImplantProfile, timeout: int=TIMEOUT) -> models.clientpb.ImplantProfile:
        ...

    async def profiles_new(self, profile: models.clientpb.ImplantProfile, timeout: int=TIMEOUT) -> models.clientpb.ImplantProfile:
        ...

    async def shellcode(self, data: bytes, function_name: str, arguments: str='', timeout: int=TIMEOUT) -> models.clientpb.ShellcodeRDI:
        ...

    async def shellcode_rdi(self, data: bytes, function_name: str, *, arguments: str='', timeout: int=TIMEOUT) -> models.clientpb.ShellcodeRDI:
        ...

    async def websites(self, timeout: int=TIMEOUT) -> list[models.clientpb.Website]:
        ...

    async def website(self, name: str, timeout: int=TIMEOUT) -> models.clientpb.Website:
        ...

    async def show_website(self, name: str, timeout: int=TIMEOUT) -> models.clientpb.Website:
        ...

    async def websites_show(self, name: str, timeout: int=TIMEOUT) -> models.clientpb.Website:
        ...

    async def update_website(self, website: models.clientpb.Website, timeout: int=TIMEOUT) -> models.clientpb.Website:
        ...

    async def remove_website(self, name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def rm_website(self, name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def websites_rm(self, name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def add_website_content(self, name: str, web_path: str, content_type: str, content: bytes, timeout: int=TIMEOUT) -> models.clientpb.Website:
        ...

    async def update_website_content(self, name: str, web_path: str, content_type: str, content: bytes, timeout: int=TIMEOUT) -> models.clientpb.Website:
        ...

    async def remove_website_content(self, name: str, paths: list[str], timeout: int=TIMEOUT) -> models.clientpb.Website:
        ...

    async def rm_website_content(self, name: str, paths: list[str], timeout: int=TIMEOUT) -> models.clientpb.Website:
        ...

    async def websites_rm_content(self, name: str, paths: list[str], timeout: int=TIMEOUT) -> models.clientpb.Website:
        ...

class Client(SliverClient):
    @classmethod
    def from_config_file(cls, filepath: os.PathLike[str] | str | None=None) -> Client:
        ...

    async def __aenter__(self) -> Client:
        ...
