# @generated by scripts/highlevelstubgen.py; DO NOT EDIT.

from __future__ import annotations

from collections.abc import AsyncGenerator

import grpc

from . import models
from ._rpc import PydanticSliverRPCStub
from .beacon import InteractiveBeacon
from .config import SliverClientConfig
from .session import InteractiveSession

KB: int
MB: int
GB: int
TIMEOUT: int

class BaseClient:
    config: SliverClientConfig

    MAX_MESSAGE_LENGTH: int

    KEEP_ALIVE_TIMEOUT: int

    CERT_COMMON_NAME: str

    def __init__(self, config: SliverClientConfig) -> None:
        ...

    def is_connected(self) -> bool:
        ...

    async def close(self) -> None:
        ...

    @property
    def target(self) -> str:
        ...

    @property
    def credentials(self) -> grpc.ChannelCredentials:
        ...

    @property
    def options(self) -> list[tuple[str, int | str]]:
        ...

    @property
    def pydantic_stub(self) -> PydanticSliverRPCStub:
        ...

class SliverClient(BaseClient):
    beacon_event_types: list[str]

    session_event_types: list[str]

    job_event_types: list[str]

    canary_event_types: list[str]

    async def connect(self) -> models.clientpb.Version:
        ...

    async def interact_session(self, session_id: str, timeout: int=TIMEOUT) -> InteractiveSession | None:
        ...

    async def interact_beacon(self, beacon_id: str, timeout: int=TIMEOUT) -> InteractiveBeacon | None:
        ...

    async def session_by_id(self, session_id: str, timeout: int=TIMEOUT) -> models.clientpb.Session | None:
        ...

    async def beacon_by_id(self, beacon_id: str, timeout: int=TIMEOUT) -> models.clientpb.Beacon | None:
        ...

    def events(self) -> AsyncGenerator[models.clientpb.Event]:
        ...

    def on(self, event_types: str | list[str]) -> AsyncGenerator[models.clientpb.Event]:
        ...

    async def version(self, timeout: int=TIMEOUT) -> models.clientpb.Version:
        ...

    async def operators(self, timeout: int=TIMEOUT) -> list[models.clientpb.Operator]:
        ...

    async def sessions(self, timeout: int=TIMEOUT) -> list[models.clientpb.Session]:
        ...

    async def rename_session(self, session_id: str, name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def kill_session(self, session_id: str, force: bool=False, timeout: int=TIMEOUT) -> None:
        ...

    async def beacons(self, timeout: int=TIMEOUT) -> list[models.clientpb.Beacon]:
        ...

    async def rename_beacon(self, beacon_id: str, name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def kill_beacon(self, beacon_id: str, timeout: int=TIMEOUT) -> None:
        ...

    async def beacon_tasks(self, beacon_id: str, timeout: int=TIMEOUT) -> list[models.clientpb.BeaconTask]:
        ...

    async def beacon_task_content(self, task_id: str, timeout: int=TIMEOUT) -> models.clientpb.BeaconTask:
        ...

    async def jobs(self, timeout: int=TIMEOUT) -> list[models.clientpb.Job]:
        ...

    async def job_by_id(self, job_id: int, timeout: int=TIMEOUT) -> models.clientpb.Job | None:
        ...

    async def job_by_port(self, job_port: int, timeout: int=TIMEOUT) -> models.clientpb.Job | None:
        ...

    async def kill_job(self, job_id: int, timeout: int=TIMEOUT) -> models.clientpb.KillJob:
        ...

    async def start_mtls_listener(self, host: str='0.0.0.0', port: int=8888, timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    async def start_wg_listener(self, tun_ip: str | None=None, host: str='0.0.0.0', port: int=53, n_port: int=8888, key_port: int=1337, timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    async def start_dns_listener(self, domains: list[str], host: str='0.0.0.0', port: int=53, canaries: bool=True, enforce_otp: bool=True, timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    async def start_http_listener(self, host: str='0.0.0.0', port: int=80, website: str='', domain: str='', timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    async def start_https_listener(self, host: str='0.0.0.0', port: int=443, website: str='', domain: str='', cert: bytes=b'', key: bytes=b'', acme: bool=False, enforce_otp: bool=True, randomize_jarm: bool=True, long_poll_timeout: int=1, long_poll_jitter: int=2, timeout: int=TIMEOUT) -> models.clientpb.ListenerJob:
        ...

    async def start_tcp_stager_listener(self, host: str, port: int, data: bytes, timeout: int=TIMEOUT) -> models.clientpb.StagerListener:
        ...

    async def generate_implant(self, config: models.clientpb.ImplantConfig, timeout: int=360) -> models.clientpb.Generate:
        ...

    async def generate_stage(self, request: models.clientpb.GenerateStageReq, timeout: int=360) -> models.clientpb.Generate:
        ...

    async def regenerate_implant(self, implant_name: str, timeout: int=TIMEOUT) -> models.clientpb.Generate:
        ...

    async def implant_builds(self, timeout: int=TIMEOUT) -> dict[str, models.clientpb.ImplantConfig]:
        ...

    async def delete_implant_build(self, implant_name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def canaries(self, timeout: int=TIMEOUT) -> list[models.clientpb.DNSCanary]:
        ...

    async def generate_wg_client_config(self, timeout: int=TIMEOUT) -> models.clientpb.WGClientConfig:
        ...

    async def generate_wg_ip(self, timeout: int=TIMEOUT) -> models.clientpb.UniqueWGIP:
        ...

    async def implant_profiles(self, timeout: int=TIMEOUT) -> list[models.clientpb.ImplantProfile]:
        ...

    async def delete_implant_profile(self, profile_name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def save_implant_profile(self, profile: models.clientpb.ImplantProfile, timeout: int=TIMEOUT) -> models.clientpb.ImplantProfile:
        ...

    async def shellcode(self, data: bytes, function_name: str, arguments: str='', timeout: int=TIMEOUT) -> models.clientpb.ShellcodeRDI:
        ...

    async def websites(self, timeout: int=TIMEOUT) -> list[models.clientpb.Website]:
        ...

    async def website(self, name: str, timeout: int=TIMEOUT) -> models.clientpb.Website:
        ...

    async def update_website(self, website: models.clientpb.Website, timeout: int=TIMEOUT) -> models.clientpb.Website:
        ...

    async def remove_website(self, name: str, timeout: int=TIMEOUT) -> None:
        ...

    async def add_website_content(self, name: str, web_path: str, content_type: str, content: bytes, timeout: int=TIMEOUT) -> models.clientpb.Website:
        ...

    async def update_website_content(self, name: str, web_path: str, content_type: str, content: bytes, timeout: int=TIMEOUT) -> models.clientpb.Website:
        ...

    async def remove_website_content(self, name: str, paths: list[str], timeout: int=TIMEOUT) -> models.clientpb.Website:
        ...
