# @generated by scripts/highlevelstubgen.py; DO NOT EDIT.

from __future__ import annotations

import os

from pydantic import BaseModel

class SliverWireGuardConfig(BaseModel):
    server_pub_key: str

    client_private_key: str

    client_pub_key: str

    client_ip: str

    server_ip: str

    def __init__(self, *, server_pub_key: str, client_private_key: str, client_pub_key: str, client_ip: str, server_ip: str) -> None: ...

class SliverClientConfig(BaseModel):
    operator: str

    lhost: str

    lport: int

    ca_certificate: str

    certificate: str

    private_key: str

    token: str

    wg: SliverWireGuardConfig | None

    def __init__(self, *, operator: str, lhost: str, lport: int, ca_certificate: str, certificate: str, private_key: str, token: str, wg: SliverWireGuardConfig | None = ...) -> None: ...

    def __str__(self) -> str:
        ...

    def __repr__(self) -> str:
        ...

    @classmethod
    def parse_config(cls, data: str | bytes) -> SliverClientConfig:
        ...

    @classmethod
    def parse_config_file(cls, filepath: os.PathLike[str] | str) -> SliverClientConfig:
        ...
