# @generated by scripts/highlevelstubgen.py; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from datetime import timedelta
from pathlib import Path

from pydantic import BaseModel

from .enums import (
    GOARCH,
    GOOS,
    C2Protocol,
    ConnectionStrategy,
    OutputFormat,
    ShellcodeBypass,
    ShellcodeCompression,
    ShellcodeEncoder,
    ShellcodeEntropy,
    ShellcodeExitOption,
    ShellcodeHeaders,
)
from .models import clientpb, commonpb

class Target(BaseModel):
    os: GOOS

    arch: GOARCH

    def __init__(self, *, os: GOOS, arch: GOARCH) -> None: ...

    @property
    def goos(self) -> GOOS:
        ...

    @property
    def goarch(self) -> GOARCH:
        ...

    @classmethod
    def current(cls) -> Target:
        ...

class C2Endpoint(BaseModel):
    protocol: C2Protocol

    url: str

    priority: int | None

    options: str

    def __init__(self, *, protocol: C2Protocol, url: str, priority: int | None = ..., options: str = ...) -> None: ...

    @classmethod
    def from_url(cls, url: str, *, priority: int | None=None, options: str='') -> C2Endpoint:
        ...

    @classmethod
    def mtls(cls, host: str, *, port: int=8888, priority: int | None=None, options: str='') -> C2Endpoint:
        ...

    @classmethod
    def wireguard(cls, host: str, *, port: int=53, priority: int | None=None, options: str='') -> C2Endpoint:
        ...

    @classmethod
    def http(cls, host: str, *, port: int=80, priority: int | None=None, options: str='', query: Mapping[str, str] | None=None) -> C2Endpoint:
        ...

    @classmethod
    def https(cls, host: str, *, port: int=443, priority: int | None=None, options: str='', query: Mapping[str, str] | None=None) -> C2Endpoint:
        ...

    @classmethod
    def dns(cls, domain: str, *, priority: int | None=None, options: str='', query: Mapping[str, str] | None=None) -> C2Endpoint:
        ...

    @classmethod
    def named_pipe(cls, host: str, pipe: str, *, priority: int | None=None, options: str='', query: Mapping[str, str] | None=None) -> C2Endpoint:
        ...

    @classmethod
    def tcp_pivot(cls, host: str, *, port: int=9898, priority: int | None=None, options: str='', query: Mapping[str, str] | None=None) -> C2Endpoint:
        ...

    def to_implant_c2(self, *, default_priority: int=0) -> clientpb.ImplantC2:
        ...

class BeaconOptions(BaseModel):
    interval: timedelta

    jitter: timedelta

    def __init__(self, *, interval: timedelta = ..., jitter: timedelta = ...) -> None: ...

class ShellcodeOptions(BaseModel):
    entropy: ShellcodeEntropy

    compression: ShellcodeCompression

    exit_option: ShellcodeExitOption

    bypass: ShellcodeBypass

    headers: ShellcodeHeaders

    thread: bool

    unicode: bool

    original_entry_point: int

    def __init__(self, *, entropy: ShellcodeEntropy = ..., compression: ShellcodeCompression = ..., exit_option: ShellcodeExitOption = ..., bypass: ShellcodeBypass = ..., headers: ShellcodeHeaders = ..., thread: bool = ..., unicode: bool = ..., original_entry_point: int = ...) -> None: ...

    def to_shellcode_config(self) -> clientpb.ShellcodeConfig:
        ...

class ImplantSpec(BaseModel):
    c2: list[C2Endpoint]

    target: Target

    beacon: BeaconOptions | None

    output_format: OutputFormat

    connection_strategy: ConnectionStrategy

    reconnect_interval: timedelta

    poll_timeout: timedelta

    max_connection_errors: int

    template_name: str

    http_c2_profile: str

    net_go_enabled: bool

    debug: bool

    evasion: bool

    obfuscate_symbols: bool

    canary_domains: list[str]

    include_protocols: set[C2Protocol]

    run_at_load: bool

    exports: list[str]

    shellcode: ShellcodeOptions | None

    shellcode_encoder: ShellcodeEncoder

    wg_peer_tun_ip: str

    wg_key_exchange_port: int

    wg_tcp_comms_port: int

    limit_domain_joined: bool

    limit_datetime: str

    limit_hostname: str

    limit_username: str

    limit_file_exists: str

    limit_locale: str

    def __init__(self, *, c2: list[C2Endpoint], target: Target = ..., beacon: BeaconOptions | None = ..., output_format: OutputFormat = ..., connection_strategy: ConnectionStrategy = ..., reconnect_interval: timedelta = ..., poll_timeout: timedelta = ..., max_connection_errors: int = ..., template_name: str = ..., http_c2_profile: str = ..., net_go_enabled: bool = ..., debug: bool = ..., evasion: bool = ..., obfuscate_symbols: bool = ..., canary_domains: list[str] = ..., include_protocols: set[C2Protocol] = ..., run_at_load: bool = ..., exports: list[str] = ..., shellcode: ShellcodeOptions | None = ..., shellcode_encoder: ShellcodeEncoder = ..., wg_peer_tun_ip: str = ..., wg_key_exchange_port: int = ..., wg_tcp_comms_port: int = ..., limit_domain_joined: bool = ..., limit_datetime: str = ..., limit_hostname: str = ..., limit_username: str = ..., limit_file_exists: str = ..., limit_locale: str = ...) -> None: ...

    def to_implant_config(self, *, base: clientpb.ImplantConfig | None=None) -> clientpb.ImplantConfig:
        ...

    def to_generate_request(self, *, name: str='', base: clientpb.ImplantConfig | None=None) -> clientpb.GenerateReq:
        ...

class GeneratedImplant(BaseModel):
    file: commonpb.File

    implant_name: str

    implant_build_id: str

    def __init__(self, *, file: commonpb.File, implant_name: str = ..., implant_build_id: str = ...) -> None: ...

    @property
    def filename(self) -> str:
        ...

    @classmethod
    def from_generate(cls, result: clientpb.Generate) -> GeneratedImplant:
        ...

    def to_generate(self) -> clientpb.Generate:
        ...

    def save(self, destination: str | Path | None=None, *, overwrite: bool=False, mode: int | None=448, create_parents: bool=True) -> Path:
        ...

class Inventory(BaseModel):
    version: clientpb.Version

    sessions: list[clientpb.Session]

    beacons: list[clientpb.Beacon]

    jobs: list[clientpb.Job]

    operators: list[clientpb.Operator]

    def __init__(self, *, version: clientpb.Version, sessions: list[clientpb.Session] = ..., beacons: list[clientpb.Beacon] = ..., jobs: list[clientpb.Job] = ..., operators: list[clientpb.Operator] = ...) -> None: ...
