# @generated by scripts/highlevelstubgen.py; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Sequence
from typing import TypeVar

from pydantic import BaseModel

_ResultT = TypeVar("_ResultT", bound=BaseModel)

class SliverError(Exception):
    ...

class NotConnectedError(SliverError, RuntimeError):
    def __init__(self, message: str='the Sliver client is not connected') -> None:
        ...

class ResourceNotFoundError(SliverError, LookupError):
    resource: str

    identifier: str | int

    def __init__(self, resource: str, identifier: str | int) -> None:
        ...

class RPCError(SliverError):
    operation: str

    details: str

    status: str | int | None

    def __init__(self, operation: str, details: str, *, status: str | int | None=None) -> None:
        ...

class CommandError(SliverError):
    operation: str

    message: str

    target_id: str | None

    result: BaseModel | None

    def __init__(self, operation: str, message: str, *, target_id: str | None=None, result: BaseModel | None=None) -> None:
        ...

class SliverTimeoutError(SliverError, TimeoutError):
    operation: str

    timeout: float | None

    def __init__(self, operation: str, timeout: float | None=None) -> None:
        ...

class CleanupError(SliverError):
    operation: str

    failures: tuple[BaseException, ...]

    def __init__(self, operation: str, failures: Sequence[BaseException]) -> None:
        ...

class UnsupportedTargetError(SliverError, ValueError):
    system: str

    machine: str

    def __init__(self, system: str, machine: str) -> None:
        ...

def raise_for_command_error(result: _ResultT, *, operation: str, target_id: str | None=None) -> _ResultT:
    ...
