# @generated by scripts/highlevelstubgen.py; DO NOT EDIT.

from __future__ import annotations

import grpc

from . import models
from .interactive import BaseInteractiveCommands

class BaseSession:
    timeout: int

    def __init__(self, session: models.clientpb.Session, channel: grpc.aio.Channel, timeout: int=60) -> None:
        ...

    @property
    def session(self) -> models.clientpb.Session:
        ...

    @property
    def session_id(self) -> str:
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def hostname(self) -> str:
        ...

    @property
    def uuid(self) -> str:
        ...

    @property
    def username(self) -> str:
        ...

    @property
    def uid(self) -> str:
        ...

    @property
    def gid(self) -> str:
        ...

    @property
    def os(self) -> str:
        ...

    @property
    def arch(self) -> str:
        ...

    @property
    def transport(self) -> str:
        ...

    @property
    def remote_address(self) -> str:
        ...

    @property
    def pid(self) -> int:
        ...

    @property
    def filename(self) -> str:
        ...

    @property
    def last_checkin(self) -> int:
        ...

    @property
    def active_c2(self) -> str:
        ...

    @property
    def version(self) -> str:
        ...

    @property
    def is_dead(self) -> bool:
        ...

    @property
    def reconnect_interval(self) -> int:
        ...

    @property
    def proxy_url(self) -> str:
        ...

class InteractiveSession(BaseSession, BaseInteractiveCommands):
    async def getsystem(self, hosting_process: str, config: models.clientpb.ImplantConfig) -> models.sliverpb.GetSystem:
        ...

    async def extensions_list(self) -> models.sliverpb.ListExtensions:
        ...

    async def pivots(self) -> list[models.sliverpb.PivotListener]:
        ...

    async def pivot_listeners(self) -> list[models.sliverpb.PivotListener]:
        ...

    async def start_service(self, name: str, description: str, exe: str, hostname: str, arguments: str) -> models.sliverpb.ServiceInfo:
        ...

    async def stop_service(self, name: str, hostname: str) -> models.sliverpb.ServiceInfo:
        ...

    async def services_start(self, name: str, *, hostname: str='localhost') -> models.sliverpb.ServiceInfo:
        ...

    async def services_stop(self, name: str, *, hostname: str='localhost') -> models.sliverpb.ServiceInfo:
        ...

    async def remove_service(self, name: str, hostname: str) -> models.sliverpb.ServiceInfo:
        ...

    async def backdoor(self, remote_path: str, profile_name: str) -> models.clientpb.Backdoor:
        ...
