# @generated by scripts/pydanticgen.py; DO NOT EDIT.
"""Static types for the concrete models in ``clientpb``."""

from __future__ import annotations

from . import commonpb as commonpb
from ._runtime import (
    ProtobufEnum,
    ProtobufModel,
)

class OutputFormat(ProtobufEnum):
    SHARED_LIB: OutputFormat
    SHELLCODE: OutputFormat
    EXECUTABLE: OutputFormat
    SERVICE: OutputFormat
    THIRD_PARTY: OutputFormat
    GO_ARCHIVE: OutputFormat

class StageProtocol(ProtobufEnum):
    TCP: StageProtocol
    HTTP: StageProtocol
    HTTPS: StageProtocol

class FileType(ProtobufEnum):
    NO_FILE: FileType
    BINARY: FileType
    TEXT: FileType

class ShellcodeEncoder(ProtobufEnum):
    NONE: ShellcodeEncoder
    SHIKATA_GA_NAI: ShellcodeEncoder
    XOR: ShellcodeEncoder
    XOR_DYNAMIC: ShellcodeEncoder

class HTTPC2SegmentType(ProtobufEnum):
    POLL: HTTPC2SegmentType
    SESSION: HTTPC2SegmentType
    CLOSE: HTTPC2SegmentType

class HashType(ProtobufEnum):
    MD5: HashType
    MD4: HashType
    SHA1: HashType
    SHA2_224: HashType
    SHA2_256: HashType
    SHA2_384: HashType
    SHA2_512: HashType
    SHA3_224: HashType
    SHA3_256: HashType
    SHA3_384: HashType
    SHA3_512: HashType
    RIPEMD_160: HashType
    BLAKE2B_256: HashType
    GOST_R_32_11_2012_256: HashType
    GOST_R_32_11_2012_512: HashType
    GOST_R_34_11_94: HashType
    GPG: HashType
    HALF_MD5: HashType
    KECCAK_224: HashType
    KECCAK_256: HashType
    KECCAK_384: HashType
    KECCAK_512: HashType
    WHIRLPOOL: HashType
    SIPHASH: HashType
    MD5_UTF16LE: HashType
    SHA1_UTF16LE: HashType
    SHA256_UTF16LE: HashType
    SHA384_UTF16LE: HashType
    SHA512_UTF16LE: HashType
    BLAKE2B_512_PW_SALT: HashType
    BLAKE2B_512_SALT_PW: HashType
    MD5_PW_SALT: HashType
    MD5_SALT_PW: HashType
    MD5_SALT_PW_SALT: HashType
    MD5_SALT_MD5_PW: HashType
    CRC32: HashType
    CRC32C: HashType
    CRC64Jones: HashType
    JAVA_OBJECT: HashType
    MURMUR: HashType
    MURMUR3: HashType
    THREE_DES: HashType
    DES: HashType
    AES_128_ECB: HashType
    AES_192_ECB: HashType
    AES_256_ECB: HashType
    CHA_CHA_20: HashType
    LINUX_KERNEL_CRYPTO_API_24: HashType
    SKIP_32: HashType
    PBKDF2_HMAC_MD5: HashType
    PBKDF2_HMAC_SHA1: HashType
    PBKDF2_HMAC_SHA256: HashType
    PBKDF2_HMAC_SHA512: HashType
    SCRYPT: HashType
    PHPASS: HashType
    TACACS_PLUS: HashType
    SIP_DIGEST: HashType
    IKE_MD5: HashType
    IKE_SHA1: HashType
    SNMP_V3_HMAC_MD5_96: HashType
    SNMP_V3_HMAC_MD5_96__SHA1_96: HashType
    SNMP_V3_HMAC_SHA1_96: HashType
    SNMP_V3_HMAC_SHA224_128: HashType
    SNMP_V3_HMAC_SHA256_192: HashType
    SNMP_V3_HMAC_SHA384_256: HashType
    SNMP_V3_HMAC_SHA512_384: HashType
    WPA_EAPOL_PBKDF2: HashType
    WPA_EAPOL_PMK: HashType
    WPA_PBKDF2_PMKID_EAPOL: HashType
    WPA_PMK_PMKID_EAPOL: HashType
    WPA_PMKID_PBKDF2: HashType
    WPA_PMKID_PMK: HashType
    IPMI2_PAKP_HMAC_SHA1: HashType
    CRAM_MD5: HashType
    JWT: HashType
    RADMIN_3: HashType
    KERBEROS_17_TGS_REP: HashType
    KERBEROS_17_PREAUTH: HashType
    KERBEROS_17_DB: HashType
    KERBEROS_18_TGS_REP: HashType
    KERBEROS_18_PREAUTH: HashType
    KERBEROS_18_DB: HashType
    KERBEROS_23_SA_REQ_PREAUTH: HashType
    KERBEROS_23_TGS_REP: HashType
    KERBEROS_23_AS_REP: HashType
    NET_NTLM_V1: HashType
    NET_NTLM_V1_NT: HashType
    NET_NTLM_V2: HashType
    NET_NTLM_V2_NT: HashType
    FLASK: HashType
    ISCSI_CHAP: HashType
    RACF: HashType
    AIX_SMD5: HashType
    AIX_SSHA1: HashType
    AIX_SSHA256: HashType
    AIX_SSHA512: HashType
    LM: HashType
    QNX_MD5: HashType
    QNX_SHA256: HashType
    QNX_SHA512: HashType
    DPAPI_V1_CTX_1_AND_2: HashType
    DPAPI_V1_CTX_3: HashType
    DPAPI_V2_CTX_1_AND_2: HashType
    DPAPI_V2_CTX_3: HashType
    GRUB_2: HashType
    MS_AZURE_SYNC: HashType
    BSDI_CRYPT: HashType
    NTLM: HashType
    RADMIN2: HashType
    SAMSUNG_ANDROID: HashType
    WINDOWS_HELLO_PIN: HashType
    WINDOWS_PHONE: HashType
    CISCO_ASA_MD5: HashType
    CISCO_IOS_PBKDF2_SHA256: HashType
    CISCO_IOS_SCRYPT: HashType
    CISCO_PIX_MD5: HashType
    CITRIX_NETSCALER_SHA1: HashType
    CITRIX_NETSCALER_SHA512: HashType
    DCC: HashType
    DCC2: HashType
    MACOS_10_8: HashType
    INVALID: HashType
    BCRYPT_UNIX: HashType
    SHA512_CRYPT_UNIX: HashType

class States(ProtobufEnum):
    IDLE: States
    CRACKING: States
    INITIALIZING: States

class CrackJobStatus(ProtobufEnum):
    IN_PROGRESS: CrackJobStatus
    COMPLETED: CrackJobStatus
    FAILED: CrackJobStatus

class CrackAttackMode(ProtobufEnum):
    STRAIGHT: CrackAttackMode
    COMBINATION: CrackAttackMode
    BRUTEFORCE: CrackAttackMode
    HYBRID_WORDLIST_MASK: CrackAttackMode
    HYBRID_MASK_WORDLIST: CrackAttackMode
    ASSOCIATION: CrackAttackMode
    NO_ATTACK: CrackAttackMode

class CrackEncoding(ProtobufEnum):
    INVALID_ENCODING: CrackEncoding
    ISO_8859_15: CrackEncoding
    UTF_32LE: CrackEncoding

class CrackOutfileFormat(ProtobufEnum):
    INVALID_FORMAT: CrackOutfileFormat
    HASH_SALT: CrackOutfileFormat
    PLAIN: CrackOutfileFormat
    HEX_PLAIN: CrackOutfileFormat
    CRACK_POS: CrackOutfileFormat
    TIMESTAMP_ABSOLUTE: CrackOutfileFormat
    TIMESTAMP_RELATIVE: CrackOutfileFormat

class CrackWorkloadProfile(ProtobufEnum):
    INVALID_WORKLOAD_PROFILE: CrackWorkloadProfile
    LOW: CrackWorkloadProfile
    DEFAULT: CrackWorkloadProfile
    HIGH: CrackWorkloadProfile
    NIGHTMARE: CrackWorkloadProfile

class CrackFileType(ProtobufEnum):
    INVALID_TYPE: CrackFileType
    WORDLIST: CrackFileType
    RULES: CrackFileType
    MARKOV_HCSTAT2: CrackFileType

class AIConversationTurnState(ProtobufEnum):
    AI_TURN_STATE_IDLE: AIConversationTurnState
    AI_TURN_STATE_IN_PROGRESS: AIConversationTurnState
    AI_TURN_STATE_FAILED: AIConversationTurnState

class AIConversationMessageKind(ProtobufEnum):
    AI_MESSAGE_KIND_CHAT: AIConversationMessageKind
    AI_MESSAGE_KIND_REASONING: AIConversationMessageKind
    AI_MESSAGE_KIND_TOOL_CALL: AIConversationMessageKind

class AIConversationMessageVisibility(ProtobufEnum):
    AI_MESSAGE_VISIBILITY_CONTEXT: AIConversationMessageVisibility
    AI_MESSAGE_VISIBILITY_UI_ONLY: AIConversationMessageVisibility

class AIConversationMessageState(ProtobufEnum):
    AI_MESSAGE_STATE_COMPLETED: AIConversationMessageState
    AI_MESSAGE_STATE_IN_PROGRESS: AIConversationMessageState
    AI_MESSAGE_STATE_FAILED: AIConversationMessageState

class AIConversationEventType(ProtobufEnum):
    AI_CONVERSATION_EVENT_TYPE_UNKNOWN: AIConversationEventType
    AI_CONVERSATION_EVENT_TYPE_CONVERSATION_UPDATED: AIConversationEventType
    AI_CONVERSATION_EVENT_TYPE_CONVERSATION_DELETED: AIConversationEventType
    AI_CONVERSATION_EVENT_TYPE_TURN_STARTED: AIConversationEventType
    AI_CONVERSATION_EVENT_TYPE_TURN_COMPLETED: AIConversationEventType
    AI_CONVERSATION_EVENT_TYPE_TURN_FAILED: AIConversationEventType
    AI_CONVERSATION_EVENT_TYPE_MESSAGE_STARTED: AIConversationEventType
    AI_CONVERSATION_EVENT_TYPE_MESSAGE_UPDATED: AIConversationEventType
    AI_CONVERSATION_EVENT_TYPE_MESSAGE_COMPLETED: AIConversationEventType

class Version(ProtobufModel):
    major: int
    minor: int
    patch: int
    commit: str
    dirty: bool
    compiled_at: int
    os: str
    arch: str
    def __init__(
        self,
        *,
        major: int = ...,
        minor: int = ...,
        patch: int = ...,
        commit: str = ...,
        dirty: bool = ...,
        compiled_at: int = ...,
        os: str = ...,
        arch: str = ...,
    ) -> None: ...

class ClientLogData(ProtobufModel):
    stream: str
    data: bytes
    def __init__(
        self,
        *,
        stream: str = ...,
        data: bytes = ...,
    ) -> None: ...

class Session(ProtobufModel):
    id: str
    name: str
    hostname: str
    uuid: str
    username: str
    uid: str
    gid: str
    os: str
    arch: str
    transport: str
    remote_address: str
    pid: int
    filename: str
    last_checkin: int
    active_c2: str
    version: str
    evasion: bool
    is_dead: bool
    reconnect_interval: int
    proxy_url: str
    burned: bool
    extensions: list[str]
    peer_id: int
    locale: str
    first_contact: int
    integrity: str
    capabilities: int
    def __init__(
        self,
        *,
        id: str = ...,
        name: str = ...,
        hostname: str = ...,
        uuid: str = ...,
        username: str = ...,
        uid: str = ...,
        gid: str = ...,
        os: str = ...,
        arch: str = ...,
        transport: str = ...,
        remote_address: str = ...,
        pid: int = ...,
        filename: str = ...,
        last_checkin: int = ...,
        active_c2: str = ...,
        version: str = ...,
        evasion: bool = ...,
        is_dead: bool = ...,
        reconnect_interval: int = ...,
        proxy_url: str = ...,
        burned: bool = ...,
        extensions: list[str] = ...,
        peer_id: int = ...,
        locale: str = ...,
        first_contact: int = ...,
        integrity: str = ...,
        capabilities: int = ...,
    ) -> None: ...

class Beacon(ProtobufModel):
    id: str
    name: str
    hostname: str
    uuid: str
    username: str
    uid: str
    gid: str
    os: str
    arch: str
    transport: str
    remote_address: str
    pid: int
    filename: str
    last_checkin: int
    active_c2: str
    version: str
    evasion: bool
    is_dead: bool
    proxy_url: str
    reconnect_interval: int
    interval: int
    jitter: int
    burned: bool
    next_checkin: int
    tasks_count: int
    tasks_count_completed: int
    locale: str
    first_contact: int
    integrity: str
    capabilities: int
    def __init__(
        self,
        *,
        id: str = ...,
        name: str = ...,
        hostname: str = ...,
        uuid: str = ...,
        username: str = ...,
        uid: str = ...,
        gid: str = ...,
        os: str = ...,
        arch: str = ...,
        transport: str = ...,
        remote_address: str = ...,
        pid: int = ...,
        filename: str = ...,
        last_checkin: int = ...,
        active_c2: str = ...,
        version: str = ...,
        evasion: bool = ...,
        is_dead: bool = ...,
        proxy_url: str = ...,
        reconnect_interval: int = ...,
        interval: int = ...,
        jitter: int = ...,
        burned: bool = ...,
        next_checkin: int = ...,
        tasks_count: int = ...,
        tasks_count_completed: int = ...,
        locale: str = ...,
        first_contact: int = ...,
        integrity: str = ...,
        capabilities: int = ...,
    ) -> None: ...

class Beacons(ProtobufModel):
    beacons: list[Beacon]
    def __init__(
        self,
        *,
        beacons: list[Beacon] = ...,
    ) -> None: ...

class BeaconTask(ProtobufModel):
    id: str
    beacon_id: str
    created_at: int
    state: str
    sent_at: int
    completed_at: int
    request: bytes
    response: bytes
    description: str
    def __init__(
        self,
        *,
        id: str = ...,
        beacon_id: str = ...,
        created_at: int = ...,
        state: str = ...,
        sent_at: int = ...,
        completed_at: int = ...,
        request: bytes = ...,
        response: bytes = ...,
        description: str = ...,
    ) -> None: ...

class BeaconTasks(ProtobufModel):
    beacon_id: str
    tasks: list[BeaconTask]
    def __init__(
        self,
        *,
        beacon_id: str = ...,
        tasks: list[BeaconTask] = ...,
    ) -> None: ...

class BeaconIntegrity(ProtobufModel):
    beacon_id: str
    integrity: str
    def __init__(
        self,
        *,
        beacon_id: str = ...,
        integrity: str = ...,
    ) -> None: ...

class ImplantC2(ProtobufModel):
    id: str
    priority: int
    url: str
    options: str
    def __init__(
        self,
        *,
        id: str = ...,
        priority: int = ...,
        url: str = ...,
        options: str = ...,
    ) -> None: ...

class ShellcodeConfig(ProtobufModel):
    entropy: int
    compress: int
    exit_opt: int
    bypass: int
    headers: int
    thread: bool
    unicode: bool
    oep: int
    def __init__(
        self,
        *,
        entropy: int = ...,
        compress: int = ...,
        exit_opt: int = ...,
        bypass: int = ...,
        headers: int = ...,
        thread: bool = ...,
        unicode: bool = ...,
        oep: int = ...,
    ) -> None: ...

class ImplantConfig(ProtobufModel):
    id: str
    implant_builds: list[ImplantBuild]
    implant_profile_id: str
    is_beacon: bool
    beacon_interval: int
    beacon_jitter: int
    goos: str
    goarch: str
    debug: bool
    evasion: bool
    obfuscate_symbols: bool
    template_name: str
    sgn_enabled: bool
    go_package: str
    include_mtls: bool
    include_http: bool
    include_wg: bool
    include_dns: bool
    include_name_pipe: bool
    include_tcp: bool
    wg_peer_tun_ip: str
    wg_key_exchange_port: int
    wg_tcp_comms_port: int
    reconnect_interval: int
    max_connection_errors: int
    poll_timeout: int
    c2: list[ImplantC2]
    canary_domains: list[str]
    connection_strategy: str
    limit_domain_joined: bool
    limit_datetime: str
    limit_hostname: str
    limit_username: str
    limit_file_exists: str
    limit_locale: str
    format: OutputFormat
    is_shared_lib: bool
    is_service: bool
    is_shellcode: bool
    run_at_load: bool
    debug_file: str
    exports: list[str]
    shellcode_config: ShellcodeConfig | None
    shellcode_encoder: ShellcodeEncoder
    httpc2_config_name: str
    net_go_enabled: bool
    traffic_encoders_enabled: bool
    traffic_encoders: list[str]
    extension: str
    assets: list[commonpb.File]
    def __init__(
        self,
        *,
        id: str = ...,
        implant_builds: list[ImplantBuild] = ...,
        implant_profile_id: str = ...,
        is_beacon: bool = ...,
        beacon_interval: int = ...,
        beacon_jitter: int = ...,
        goos: str = ...,
        goarch: str = ...,
        debug: bool = ...,
        evasion: bool = ...,
        obfuscate_symbols: bool = ...,
        template_name: str = ...,
        sgn_enabled: bool = ...,
        go_package: str = ...,
        include_mtls: bool = ...,
        include_http: bool = ...,
        include_wg: bool = ...,
        include_dns: bool = ...,
        include_name_pipe: bool = ...,
        include_tcp: bool = ...,
        wg_peer_tun_ip: str = ...,
        wg_key_exchange_port: int = ...,
        wg_tcp_comms_port: int = ...,
        reconnect_interval: int = ...,
        max_connection_errors: int = ...,
        poll_timeout: int = ...,
        c2: list[ImplantC2] = ...,
        canary_domains: list[str] = ...,
        connection_strategy: str = ...,
        limit_domain_joined: bool = ...,
        limit_datetime: str = ...,
        limit_hostname: str = ...,
        limit_username: str = ...,
        limit_file_exists: str = ...,
        limit_locale: str = ...,
        format: OutputFormat = ...,
        is_shared_lib: bool = ...,
        is_service: bool = ...,
        is_shellcode: bool = ...,
        run_at_load: bool = ...,
        debug_file: str = ...,
        exports: list[str] = ...,
        shellcode_config: ShellcodeConfig | None = ...,
        shellcode_encoder: ShellcodeEncoder = ...,
        httpc2_config_name: str = ...,
        net_go_enabled: bool = ...,
        traffic_encoders_enabled: bool = ...,
        traffic_encoders: list[str] = ...,
        extension: str = ...,
        assets: list[commonpb.File] = ...,
    ) -> None: ...

class SpoofMetadataFile(ProtobufModel):
    name: str
    data: bytes
    def __init__(
        self,
        *,
        name: str = ...,
        data: bytes = ...,
    ) -> None: ...

class IMAGE_RESOURCE_DIRECTORY(ProtobufModel):
    characteristics: int
    time_date_stamp: int
    major_version: int
    minor_version: int
    number_of_named_entries: int
    number_of_id_entries: int
    def __init__(
        self,
        *,
        characteristics: int = ...,
        time_date_stamp: int = ...,
        major_version: int = ...,
        minor_version: int = ...,
        number_of_named_entries: int = ...,
        number_of_id_entries: int = ...,
    ) -> None: ...

class IMAGE_RESOURCE_DIRECTORY_ENTRY(ProtobufModel):
    name: int
    offset_to_data: int
    def __init__(
        self,
        *,
        name: int = ...,
        offset_to_data: int = ...,
    ) -> None: ...

class IMAGE_RESOURCE_DATA_ENTRY(ProtobufModel):
    offset_to_data: int
    size: int
    code_page: int
    reserved: int
    def __init__(
        self,
        *,
        offset_to_data: int = ...,
        size: int = ...,
        code_page: int = ...,
        reserved: int = ...,
    ) -> None: ...

class IMAGE_EXPORT_DIRECTORY(ProtobufModel):
    characteristics: int
    time_date_stamp: int
    major_version: int
    minor_version: int
    name: int
    base: int
    number_of_functions: int
    number_of_names: int
    address_of_functions: int
    address_of_names: int
    address_of_name_ordinals: int
    def __init__(
        self,
        *,
        characteristics: int = ...,
        time_date_stamp: int = ...,
        major_version: int = ...,
        minor_version: int = ...,
        name: int = ...,
        base: int = ...,
        number_of_functions: int = ...,
        number_of_names: int = ...,
        address_of_functions: int = ...,
        address_of_names: int = ...,
        address_of_name_ordinals: int = ...,
    ) -> None: ...

class PESpoofMetadataConfig(ProtobufModel):
    source: SpoofMetadataFile | None
    icon: SpoofMetadataFile | None
    resource_directory: IMAGE_RESOURCE_DIRECTORY | None
    resource_directory_entries: list[IMAGE_RESOURCE_DIRECTORY_ENTRY]
    resource_data_entries: list[IMAGE_RESOURCE_DATA_ENTRY]
    export_directory: IMAGE_EXPORT_DIRECTORY | None
    def __init__(
        self,
        *,
        source: SpoofMetadataFile | None = ...,
        icon: SpoofMetadataFile | None = ...,
        resource_directory: IMAGE_RESOURCE_DIRECTORY | None = ...,
        resource_directory_entries: list[IMAGE_RESOURCE_DIRECTORY_ENTRY] = ...,
        resource_data_entries: list[IMAGE_RESOURCE_DATA_ENTRY] = ...,
        export_directory: IMAGE_EXPORT_DIRECTORY | None = ...,
    ) -> None: ...

class SpoofMetadataConfig(ProtobufModel):
    pe: PESpoofMetadataConfig | None
    def __init__(
        self,
        *,
        pe: PESpoofMetadataConfig | None = ...,
    ) -> None: ...

class TrafficEncoder(ProtobufModel):
    id: int
    wasm: commonpb.File | None
    skip_tests: bool
    test_id: str
    def __init__(
        self,
        *,
        id: int = ...,
        wasm: commonpb.File | None = ...,
        skip_tests: bool = ...,
        test_id: str = ...,
    ) -> None: ...

class TrafficEncoderMap(ProtobufModel):
    encoders: dict[str, TrafficEncoder]
    def __init__(
        self,
        *,
        encoders: dict[str, TrafficEncoder] = ...,
    ) -> None: ...

class TrafficEncoderTest(ProtobufModel):
    name: str
    completed: bool
    success: bool
    duration: int
    err: str
    sample: bytes
    def __init__(
        self,
        *,
        name: str = ...,
        completed: bool = ...,
        success: bool = ...,
        duration: int = ...,
        err: str = ...,
        sample: bytes = ...,
    ) -> None: ...

class TrafficEncoderTests(ProtobufModel):
    encoder: TrafficEncoder | None
    tests: list[TrafficEncoderTest]
    total_duration: int
    total_tests: int
    def __init__(
        self,
        *,
        encoder: TrafficEncoder | None = ...,
        tests: list[TrafficEncoderTest] = ...,
        total_duration: int = ...,
        total_tests: int = ...,
    ) -> None: ...

class ExternalImplantConfig(ProtobufModel):
    config: ImplantConfig | None
    build: ImplantBuild | None
    httpc2: HTTPC2Config | None
    encoders: dict[str, int]
    def __init__(
        self,
        *,
        config: ImplantConfig | None = ...,
        build: ImplantBuild | None = ...,
        httpc2: HTTPC2Config | None = ...,
        encoders: dict[str, int] = ...,
    ) -> None: ...

class ExternalImplantBinary(ProtobufModel):
    name: str
    implant_build_id: str
    file: commonpb.File | None
    def __init__(
        self,
        *,
        name: str = ...,
        implant_build_id: str = ...,
        file: commonpb.File | None = ...,
    ) -> None: ...

class ImplantBuilds(ProtobufModel):
    configs: dict[str, ImplantConfig]
    resource_i_ds: dict[str, ResourceID]
    staged: dict[str, bool]
    def __init__(
        self,
        *,
        configs: dict[str, ImplantConfig] = ...,
        resource_i_ds: dict[str, ResourceID] = ...,
        staged: dict[str, bool] = ...,
    ) -> None: ...

class ImplantStageReq(ProtobufModel):
    build: list[str]
    def __init__(
        self,
        *,
        build: list[str] = ...,
    ) -> None: ...

class ImplantBuild(ProtobufModel):
    id: str
    name: str
    md5: str
    sha1: str
    sha256: str
    burned: bool
    implant_id: int
    implant_config_id: str
    age_server_public_key: str
    peer_public_key: str
    peer_private_key: str
    peer_public_key_signature: str
    minisign_server_public_key: str
    peer_public_key_digest: str
    wg_implant_priv_key: str
    wg_server_pub_key: str
    mtls_ca_cert: str
    mtls_cert: str
    mtls_key: str
    stage: bool
    def __init__(
        self,
        *,
        id: str = ...,
        name: str = ...,
        md5: str = ...,
        sha1: str = ...,
        sha256: str = ...,
        burned: bool = ...,
        implant_id: int = ...,
        implant_config_id: str = ...,
        age_server_public_key: str = ...,
        peer_public_key: str = ...,
        peer_private_key: str = ...,
        peer_public_key_signature: str = ...,
        minisign_server_public_key: str = ...,
        peer_public_key_digest: str = ...,
        wg_implant_priv_key: str = ...,
        wg_server_pub_key: str = ...,
        mtls_ca_cert: str = ...,
        mtls_cert: str = ...,
        mtls_key: str = ...,
        stage: bool = ...,
    ) -> None: ...

class CompilerTarget(ProtobufModel):
    goos: str
    goarch: str
    format: OutputFormat
    def __init__(
        self,
        *,
        goos: str = ...,
        goarch: str = ...,
        format: OutputFormat = ...,
    ) -> None: ...

class CrossCompiler(ProtobufModel):
    target_goos: str
    target_goarch: str
    cc_path: str
    cxx_path: str
    def __init__(
        self,
        *,
        target_goos: str = ...,
        target_goarch: str = ...,
        cc_path: str = ...,
        cxx_path: str = ...,
    ) -> None: ...

class Compiler(ProtobufModel):
    goos: str
    goarch: str
    targets: list[CompilerTarget]
    cross_compilers: list[CrossCompiler]
    unsupported_targets: list[CompilerTarget]
    def __init__(
        self,
        *,
        goos: str = ...,
        goarch: str = ...,
        targets: list[CompilerTarget] = ...,
        cross_compilers: list[CrossCompiler] = ...,
        unsupported_targets: list[CompilerTarget] = ...,
    ) -> None: ...

class DeleteReq(ProtobufModel):
    name: str
    def __init__(
        self,
        *,
        name: str = ...,
    ) -> None: ...

class DNSCanary(ProtobufModel):
    id: str
    implant_name: str
    domain: str
    triggered: bool
    first_triggered: str
    latest_trigger: str
    count: int
    def __init__(
        self,
        *,
        id: str = ...,
        implant_name: str = ...,
        domain: str = ...,
        triggered: bool = ...,
        first_triggered: str = ...,
        latest_trigger: str = ...,
        count: int = ...,
    ) -> None: ...

class Canaries(ProtobufModel):
    canaries: list[DNSCanary]
    def __init__(
        self,
        *,
        canaries: list[DNSCanary] = ...,
    ) -> None: ...

class UniqueWGIP(ProtobufModel):
    ip: str
    def __init__(
        self,
        *,
        ip: str = ...,
    ) -> None: ...

class ImplantProfile(ProtobufModel):
    id: str
    name: str
    config: ImplantConfig | None
    def __init__(
        self,
        *,
        id: str = ...,
        name: str = ...,
        config: ImplantConfig | None = ...,
    ) -> None: ...

class ImplantProfiles(ProtobufModel):
    profiles: list[ImplantProfile]
    def __init__(
        self,
        *,
        profiles: list[ImplantProfile] = ...,
    ) -> None: ...

class RegenerateReq(ProtobufModel):
    implant_name: str
    def __init__(
        self,
        *,
        implant_name: str = ...,
    ) -> None: ...

class Job(ProtobufModel):
    id: int
    name: str
    description: str
    protocol: str
    port: int
    domains: list[str]
    profile_name: str
    def __init__(
        self,
        *,
        id: int = ...,
        name: str = ...,
        description: str = ...,
        protocol: str = ...,
        port: int = ...,
        domains: list[str] = ...,
        profile_name: str = ...,
    ) -> None: ...

class Jobs(ProtobufModel):
    active: list[Job]
    def __init__(
        self,
        *,
        active: list[Job] = ...,
    ) -> None: ...

class KillJobReq(ProtobufModel):
    id: int
    def __init__(
        self,
        *,
        id: int = ...,
    ) -> None: ...

class RestartJobReq(ProtobufModel):
    job_i_ds: list[int]
    def __init__(
        self,
        *,
        job_i_ds: list[int] = ...,
    ) -> None: ...

class KillJob(ProtobufModel):
    id: int
    success: bool
    def __init__(
        self,
        *,
        id: int = ...,
        success: bool = ...,
    ) -> None: ...

class ListenerJob(ProtobufModel):
    id: str
    type: str
    job_id: int
    mtls_conf: MTLSListenerReq | None
    wg_conf: WGListenerReq | None
    dns_conf: DNSListenerReq | None
    http_conf: HTTPListenerReq | None
    multi_conf: MultiplayerListenerReq | None
    tcp_conf: StagerListenerReq | None
    def __init__(
        self,
        *,
        id: str = ...,
        type: str = ...,
        job_id: int = ...,
        mtls_conf: MTLSListenerReq | None = ...,
        wg_conf: WGListenerReq | None = ...,
        dns_conf: DNSListenerReq | None = ...,
        http_conf: HTTPListenerReq | None = ...,
        multi_conf: MultiplayerListenerReq | None = ...,
        tcp_conf: StagerListenerReq | None = ...,
    ) -> None: ...

class MultiplayerListenerReq(ProtobufModel):
    host: str
    port: int
    wire_guard: bool
    def __init__(
        self,
        *,
        host: str = ...,
        port: int = ...,
        wire_guard: bool = ...,
    ) -> None: ...

class MTLSListenerReq(ProtobufModel):
    host: str
    port: int
    def __init__(
        self,
        *,
        host: str = ...,
        port: int = ...,
    ) -> None: ...

class WGListenerReq(ProtobufModel):
    host: str
    port: int
    tun_ip: str
    n_port: int
    key_port: int
    def __init__(
        self,
        *,
        host: str = ...,
        port: int = ...,
        tun_ip: str = ...,
        n_port: int = ...,
        key_port: int = ...,
    ) -> None: ...

class DNSListenerReq(ProtobufModel):
    domains: list[str]
    canaries: bool
    host: str
    port: int
    enforce_otp: bool
    def __init__(
        self,
        *,
        domains: list[str] = ...,
        canaries: bool = ...,
        host: str = ...,
        port: int = ...,
        enforce_otp: bool = ...,
    ) -> None: ...

class HTTPListenerReq(ProtobufModel):
    domain: str
    host: str
    port: int
    secure: bool
    website: str
    cert: bytes
    key: bytes
    acme: bool
    enforce_otp: bool
    long_poll_timeout: int
    long_poll_jitter: int
    randomize_jarm: bool
    def __init__(
        self,
        *,
        domain: str = ...,
        host: str = ...,
        port: int = ...,
        secure: bool = ...,
        website: str = ...,
        cert: bytes = ...,
        key: bytes = ...,
        acme: bool = ...,
        enforce_otp: bool = ...,
        long_poll_timeout: int = ...,
        long_poll_jitter: int = ...,
        randomize_jarm: bool = ...,
    ) -> None: ...

class NamedPipesReq(ProtobufModel):
    pipe_name: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        pipe_name: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class NamedPipes(ProtobufModel):
    success: bool
    err: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        success: bool = ...,
        err: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class TCPPivotReq(ProtobufModel):
    address: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        address: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class TCPPivot(ProtobufModel):
    success: bool
    err: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        success: bool = ...,
        err: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class Sessions(ProtobufModel):
    sessions: list[Session]
    def __init__(
        self,
        *,
        sessions: list[Session] = ...,
    ) -> None: ...

class RenameReq(ProtobufModel):
    session_id: str
    beacon_id: str
    name: str
    def __init__(
        self,
        *,
        session_id: str = ...,
        beacon_id: str = ...,
        name: str = ...,
    ) -> None: ...

class GenerateReq(ProtobufModel):
    config: ImplantConfig | None
    name: str
    def __init__(
        self,
        *,
        config: ImplantConfig | None = ...,
        name: str = ...,
    ) -> None: ...

class GenerateStageReq(ProtobufModel):
    profile: str
    name: str
    aes_encrypt_key: str
    aes_encrypt_iv: str
    rc4_encrypt_key: str
    prepend_size: bool
    compress_f: str
    compress: str
    def __init__(
        self,
        *,
        profile: str = ...,
        name: str = ...,
        aes_encrypt_key: str = ...,
        aes_encrypt_iv: str = ...,
        rc4_encrypt_key: str = ...,
        prepend_size: bool = ...,
        compress_f: str = ...,
        compress: str = ...,
    ) -> None: ...

class Generate(ProtobufModel):
    file: commonpb.File | None
    implant_name: str
    implant_build_id: str
    def __init__(
        self,
        *,
        file: commonpb.File | None = ...,
        implant_name: str = ...,
        implant_build_id: str = ...,
    ) -> None: ...

class GenerateSpoofMetadataReq(ProtobufModel):
    implant_build_id: str
    implant_name: str
    resource_id: int
    spoof_metadata: SpoofMetadataConfig | None
    def __init__(
        self,
        *,
        implant_build_id: str = ...,
        implant_name: str = ...,
        resource_id: int = ...,
        spoof_metadata: SpoofMetadataConfig | None = ...,
    ) -> None: ...

class MSFReq(ProtobufModel):
    payload: str
    l_host: str
    l_port: int
    encoder: str
    iterations: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        payload: str = ...,
        l_host: str = ...,
        l_port: int = ...,
        encoder: str = ...,
        iterations: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class MSFRemoteReq(ProtobufModel):
    payload: str
    l_host: str
    l_port: int
    encoder: str
    iterations: int
    pid: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        payload: str = ...,
        l_host: str = ...,
        l_port: int = ...,
        encoder: str = ...,
        iterations: int = ...,
        pid: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class StagerListenerReq(ProtobufModel):
    protocol: StageProtocol
    host: str
    port: int
    data: bytes
    profile_name: str
    def __init__(
        self,
        *,
        protocol: StageProtocol = ...,
        host: str = ...,
        port: int = ...,
        data: bytes = ...,
        profile_name: str = ...,
    ) -> None: ...

class StagerListener(ProtobufModel):
    job_id: int
    def __init__(
        self,
        *,
        job_id: int = ...,
    ) -> None: ...

class ShellcodeRDIReq(ProtobufModel):
    data: bytes
    function_name: str
    arguments: str
    def __init__(
        self,
        *,
        data: bytes = ...,
        function_name: str = ...,
        arguments: str = ...,
    ) -> None: ...

class ShellcodeRDI(ProtobufModel):
    data: bytes
    def __init__(
        self,
        *,
        data: bytes = ...,
    ) -> None: ...

class GetSystemReq(ProtobufModel):
    hosting_process: str
    config: ImplantConfig | None
    name: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        hosting_process: str = ...,
        config: ImplantConfig | None = ...,
        name: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class MigrateReq(ProtobufModel):
    pid: int
    config: ImplantConfig | None
    encoder: ShellcodeEncoder
    name: str
    proc_name: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        pid: int = ...,
        config: ImplantConfig | None = ...,
        encoder: ShellcodeEncoder = ...,
        name: str = ...,
        proc_name: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class CreateTunnelReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class CreateTunnel(ProtobufModel):
    session_id: int
    tunnel_id: int
    def __init__(
        self,
        *,
        session_id: int = ...,
        tunnel_id: int = ...,
    ) -> None: ...

class CloseTunnelReq(ProtobufModel):
    tunnel_id: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        tunnel_id: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class PivotGraphEntry(ProtobufModel):
    peer_id: int
    session: Session | None
    name: str
    children: list[PivotGraphEntry]
    def __init__(
        self,
        *,
        peer_id: int = ...,
        session: Session | None = ...,
        name: str = ...,
        children: list[PivotGraphEntry] = ...,
    ) -> None: ...

class PivotGraph(ProtobufModel):
    children: list[PivotGraphEntry]
    def __init__(
        self,
        *,
        children: list[PivotGraphEntry] = ...,
    ) -> None: ...

class Client(ProtobufModel):
    id: int
    name: str
    operator: Operator | None
    def __init__(
        self,
        *,
        id: int = ...,
        name: str = ...,
        operator: Operator | None = ...,
    ) -> None: ...

class Event(ProtobufModel):
    event_type: str
    session: Session | None
    job: Job | None
    client: Client | None
    data: bytes
    err: str
    def __init__(
        self,
        *,
        event_type: str = ...,
        session: Session | None = ...,
        job: Job | None = ...,
        client: Client | None = ...,
        data: bytes = ...,
        err: str = ...,
    ) -> None: ...

class Operators(ProtobufModel):
    operators: list[Operator]
    def __init__(
        self,
        *,
        operators: list[Operator] = ...,
    ) -> None: ...

class Operator(ProtobufModel):
    online: bool
    name: str
    def __init__(
        self,
        *,
        online: bool = ...,
        name: str = ...,
    ) -> None: ...

class WebContent(ProtobufModel):
    id: str
    website_id: str
    path: str
    content_type: str
    size: int
    original_file: str
    sha256: str
    content: bytes
    def __init__(
        self,
        *,
        id: str = ...,
        website_id: str = ...,
        path: str = ...,
        content_type: str = ...,
        size: int = ...,
        original_file: str = ...,
        sha256: str = ...,
        content: bytes = ...,
    ) -> None: ...

class WebsiteAddContent(ProtobufModel):
    name: str
    contents: dict[str, WebContent]
    def __init__(
        self,
        *,
        name: str = ...,
        contents: dict[str, WebContent] = ...,
    ) -> None: ...

class WebsiteRemoveContent(ProtobufModel):
    name: str
    paths: list[str]
    def __init__(
        self,
        *,
        name: str = ...,
        paths: list[str] = ...,
    ) -> None: ...

class Website(ProtobufModel):
    id: str
    name: str
    contents: dict[str, WebContent]
    def __init__(
        self,
        *,
        id: str = ...,
        name: str = ...,
        contents: dict[str, WebContent] = ...,
    ) -> None: ...

class Websites(ProtobufModel):
    websites: list[Website]
    def __init__(
        self,
        *,
        websites: list[Website] = ...,
    ) -> None: ...

class WGClientConfig(ProtobufModel):
    server_pub_key: str
    client_private_key: str
    client_pub_key: str
    client_ip: str
    def __init__(
        self,
        *,
        server_pub_key: str = ...,
        client_private_key: str = ...,
        client_pub_key: str = ...,
        client_ip: str = ...,
    ) -> None: ...

class Loot(ProtobufModel):
    id: str
    name: str
    file_type: FileType
    origin_host_uuid: str
    size: int
    file: commonpb.File | None
    def __init__(
        self,
        *,
        id: str = ...,
        name: str = ...,
        file_type: FileType = ...,
        origin_host_uuid: str = ...,
        size: int = ...,
        file: commonpb.File | None = ...,
    ) -> None: ...

class AllLoot(ProtobufModel):
    loot: list[Loot]
    def __init__(
        self,
        *,
        loot: list[Loot] = ...,
    ) -> None: ...

class IOC(ProtobufModel):
    path: str
    file_hash: str
    id: str
    def __init__(
        self,
        *,
        path: str = ...,
        file_hash: str = ...,
        id: str = ...,
    ) -> None: ...

class ExtensionData(ProtobufModel):
    output: str
    def __init__(
        self,
        *,
        output: str = ...,
    ) -> None: ...

class Host(ProtobufModel):
    id: str
    hostname: str
    host_uuid: str
    os_version: str
    io_cs: list[IOC]
    extension_data: dict[str, ExtensionData]
    locale: str
    first_contact: int
    def __init__(
        self,
        *,
        id: str = ...,
        hostname: str = ...,
        host_uuid: str = ...,
        os_version: str = ...,
        io_cs: list[IOC] = ...,
        extension_data: dict[str, ExtensionData] = ...,
        locale: str = ...,
        first_contact: int = ...,
    ) -> None: ...

class AllHosts(ProtobufModel):
    hosts: list[Host]
    def __init__(
        self,
        *,
        hosts: list[Host] = ...,
    ) -> None: ...

class DllHijackReq(ProtobufModel):
    reference_dll_path: str
    target_location: str
    reference_dll: bytes
    target_dll: bytes
    profile_name: str
    name: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        reference_dll_path: str = ...,
        target_location: str = ...,
        reference_dll: bytes = ...,
        target_dll: bytes = ...,
        profile_name: str = ...,
        name: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class DllHijack(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class BackdoorReq(ProtobufModel):
    file_path: str
    profile_name: str
    name: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        file_path: str = ...,
        profile_name: str = ...,
        name: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Backdoor(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ShellcodeEncodeReq(ProtobufModel):
    encoder: ShellcodeEncoder
    architecture: str
    iterations: int
    bad_chars: bytes
    data: bytes
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        encoder: ShellcodeEncoder = ...,
        architecture: str = ...,
        iterations: int = ...,
        bad_chars: bytes = ...,
        data: bytes = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class ShellcodeEncode(ProtobufModel):
    data: bytes
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        data: bytes = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ShellcodeEncoderArchMap(ProtobufModel):
    encoders: dict[str, ShellcodeEncoder]
    descriptions: dict[str, str]
    def __init__(
        self,
        *,
        encoders: dict[str, ShellcodeEncoder] = ...,
        descriptions: dict[str, str] = ...,
    ) -> None: ...

class ShellcodeEncoderMap(ProtobufModel):
    encoders: dict[str, ShellcodeEncoderArchMap]
    def __init__(
        self,
        *,
        encoders: dict[str, ShellcodeEncoderArchMap] = ...,
    ) -> None: ...

class ExternalGenerateReq(ProtobufModel):
    config: ImplantConfig | None
    builder_name: str
    name: str
    def __init__(
        self,
        *,
        config: ImplantConfig | None = ...,
        builder_name: str = ...,
        name: str = ...,
    ) -> None: ...

class Builders(ProtobufModel):
    builders: list[Builder]
    def __init__(
        self,
        *,
        builders: list[Builder] = ...,
    ) -> None: ...

class Builder(ProtobufModel):
    name: str
    operator_name: str
    goos: str
    goarch: str
    templates: list[str]
    targets: list[CompilerTarget]
    cross_compilers: list[CrossCompiler]
    def __init__(
        self,
        *,
        name: str = ...,
        operator_name: str = ...,
        goos: str = ...,
        goarch: str = ...,
        templates: list[str] = ...,
        targets: list[CompilerTarget] = ...,
        cross_compilers: list[CrossCompiler] = ...,
    ) -> None: ...

class HTTPC2Configs(ProtobufModel):
    configs: list[HTTPC2Config]
    def __init__(
        self,
        *,
        configs: list[HTTPC2Config] = ...,
    ) -> None: ...

class C2ProfileReq(ProtobufModel):
    name: str
    def __init__(
        self,
        *,
        name: str = ...,
    ) -> None: ...

class HTTPC2ConfigReq(ProtobufModel):
    overwrite: bool
    c2_config: HTTPC2Config | None
    def __init__(
        self,
        *,
        overwrite: bool = ...,
        c2_config: HTTPC2Config | None = ...,
    ) -> None: ...

class HTTPC2Config(ProtobufModel):
    id: str
    created: int
    name: str
    server_config: HTTPC2ServerConfig | None
    implant_config: HTTPC2ImplantConfig | None
    def __init__(
        self,
        *,
        id: str = ...,
        created: int = ...,
        name: str = ...,
        server_config: HTTPC2ServerConfig | None = ...,
        implant_config: HTTPC2ImplantConfig | None = ...,
    ) -> None: ...

class HTTPC2ServerConfig(ProtobufModel):
    id: str
    random_version_headers: bool
    headers: list[HTTPC2Header]
    cookies: list[HTTPC2Cookie]
    def __init__(
        self,
        *,
        id: str = ...,
        random_version_headers: bool = ...,
        headers: list[HTTPC2Header] = ...,
        cookies: list[HTTPC2Cookie] = ...,
    ) -> None: ...

class HTTPC2ImplantConfig(ProtobufModel):
    id: str
    user_agent: str
    chrome_base_version: int
    mac_os_version: str
    nonce_query_arg_chars: str
    extra_url_parameters: list[HTTPC2URLParameter]
    headers: list[HTTPC2Header]
    max_file_gen: int
    min_file_gen: int
    max_path_gen: int
    min_path_gen: int
    max_path_length: int
    min_path_length: int
    extensions: list[str]
    path_segments: list[HTTPC2PathSegment]
    nonce_query_length: int
    nonce_mode: str
    def __init__(
        self,
        *,
        id: str = ...,
        user_agent: str = ...,
        chrome_base_version: int = ...,
        mac_os_version: str = ...,
        nonce_query_arg_chars: str = ...,
        extra_url_parameters: list[HTTPC2URLParameter] = ...,
        headers: list[HTTPC2Header] = ...,
        max_file_gen: int = ...,
        min_file_gen: int = ...,
        max_path_gen: int = ...,
        min_path_gen: int = ...,
        max_path_length: int = ...,
        min_path_length: int = ...,
        extensions: list[str] = ...,
        path_segments: list[HTTPC2PathSegment] = ...,
        nonce_query_length: int = ...,
        nonce_mode: str = ...,
    ) -> None: ...

class HTTPC2Cookie(ProtobufModel):
    id: str
    name: str
    def __init__(
        self,
        *,
        id: str = ...,
        name: str = ...,
    ) -> None: ...

class HTTPC2Header(ProtobufModel):
    id: str
    method: str
    name: str
    value: str
    probability: int
    def __init__(
        self,
        *,
        id: str = ...,
        method: str = ...,
        name: str = ...,
        value: str = ...,
        probability: int = ...,
    ) -> None: ...

class HTTPC2URLParameter(ProtobufModel):
    id: str
    method: str
    name: str
    value: str
    probability: int
    def __init__(
        self,
        *,
        id: str = ...,
        method: str = ...,
        name: str = ...,
        value: str = ...,
        probability: int = ...,
    ) -> None: ...

class HTTPC2PathSegment(ProtobufModel):
    id: str
    is_file: bool
    value: str
    def __init__(
        self,
        *,
        id: str = ...,
        is_file: bool = ...,
        value: str = ...,
    ) -> None: ...

class Credential(ProtobufModel):
    id: str
    username: str
    plaintext: str
    hash: str
    hash_type: HashType
    is_cracked: bool
    origin_host_uuid: str
    collection: str
    def __init__(
        self,
        *,
        id: str = ...,
        username: str = ...,
        plaintext: str = ...,
        hash: str = ...,
        hash_type: HashType = ...,
        is_cracked: bool = ...,
        origin_host_uuid: str = ...,
        collection: str = ...,
    ) -> None: ...

class Credentials(ProtobufModel):
    credentials: list[Credential]
    def __init__(
        self,
        *,
        credentials: list[Credential] = ...,
    ) -> None: ...

class Crackstations(ProtobufModel):
    crackstations: list[Crackstation]
    def __init__(
        self,
        *,
        crackstations: list[Crackstation] = ...,
    ) -> None: ...

class CrackstationStatus(ProtobufModel):
    name: str
    host_uuid: str
    state: States
    current_crack_job_id: str
    is_syncing: bool
    syncing: CrackSyncStatus | None
    def __init__(
        self,
        *,
        name: str = ...,
        host_uuid: str = ...,
        state: States = ...,
        current_crack_job_id: str = ...,
        is_syncing: bool = ...,
        syncing: CrackSyncStatus | None = ...,
    ) -> None: ...

class CrackSyncStatus(ProtobufModel):
    speed: float
    progress: dict[str, float]
    def __init__(
        self,
        *,
        speed: float = ...,
        progress: dict[str, float] = ...,
    ) -> None: ...

class CrackBenchmark(ProtobufModel):
    name: str
    host_uuid: str
    benchmarks: dict[int, int]
    def __init__(
        self,
        *,
        name: str = ...,
        host_uuid: str = ...,
        benchmarks: dict[int, int] = ...,
    ) -> None: ...

class CrackTask(ProtobufModel):
    id: str
    host_uuid: str
    created_at: int
    started_at: int
    completed_at: int
    err: str
    command: CrackCommand | None
    def __init__(
        self,
        *,
        id: str = ...,
        host_uuid: str = ...,
        created_at: int = ...,
        started_at: int = ...,
        completed_at: int = ...,
        err: str = ...,
        command: CrackCommand | None = ...,
    ) -> None: ...

class Crackstation(ProtobufModel):
    id: str
    name: str
    operator_name: str
    goos: str
    goarch: str
    hashcat_version: str
    host_uuid: str
    version: str
    benchmarks: dict[int, int]
    cuda: list[CUDABackendInfo]
    metal: list[MetalBackendInfo]
    open_cl: list[OpenCLBackendInfo]
    def __init__(
        self,
        *,
        id: str = ...,
        name: str = ...,
        operator_name: str = ...,
        goos: str = ...,
        goarch: str = ...,
        hashcat_version: str = ...,
        host_uuid: str = ...,
        version: str = ...,
        benchmarks: dict[int, int] = ...,
        cuda: list[CUDABackendInfo] = ...,
        metal: list[MetalBackendInfo] = ...,
        open_cl: list[OpenCLBackendInfo] = ...,
    ) -> None: ...

class CUDABackendInfo(ProtobufModel):
    type: str
    vendor_id: int
    vendor: str
    name: str
    version: str
    processors: int
    clock: int
    memory_total: str
    memory_free: str
    cuda_version: str
    def __init__(
        self,
        *,
        type: str = ...,
        vendor_id: int = ...,
        vendor: str = ...,
        name: str = ...,
        version: str = ...,
        processors: int = ...,
        clock: int = ...,
        memory_total: str = ...,
        memory_free: str = ...,
        cuda_version: str = ...,
    ) -> None: ...

class OpenCLBackendInfo(ProtobufModel):
    type: str
    vendor_id: int
    vendor: str
    name: str
    version: str
    processors: int
    clock: int
    memory_total: str
    memory_free: str
    open_cl_version: str
    open_cl_driver_version: str
    def __init__(
        self,
        *,
        type: str = ...,
        vendor_id: int = ...,
        vendor: str = ...,
        name: str = ...,
        version: str = ...,
        processors: int = ...,
        clock: int = ...,
        memory_total: str = ...,
        memory_free: str = ...,
        open_cl_version: str = ...,
        open_cl_driver_version: str = ...,
    ) -> None: ...

class MetalBackendInfo(ProtobufModel):
    type: str
    vendor_id: int
    vendor: str
    name: str
    version: str
    processors: int
    clock: int
    memory_total: str
    memory_free: str
    metal_version: str
    def __init__(
        self,
        *,
        type: str = ...,
        vendor_id: int = ...,
        vendor: str = ...,
        name: str = ...,
        version: str = ...,
        processors: int = ...,
        clock: int = ...,
        memory_total: str = ...,
        memory_free: str = ...,
        metal_version: str = ...,
    ) -> None: ...

class CrackCommand(ProtobufModel):
    attack_mode: CrackAttackMode
    hash_type: HashType
    hashes: list[str]
    quiet: bool
    hex_charset: bool
    hex_salt: bool
    hex_wordlist: bool
    force: bool
    deprecated_check_disable: bool
    status: bool
    status_json: bool
    status_timer: int
    stdin_timeout_abort: int
    machine_readable: bool
    keep_guessing: bool
    self_test_disable: bool
    loopback: bool
    markov_hcstat2: bytes
    markov_disable: bool
    markov_classic: bool
    markov_inverse: bool
    markov_threshold: int
    runtime: int
    session: str
    restore: bool
    restore_disable: bool
    restore_file: bytes
    outfile_format: list[CrackOutfileFormat]
    outfile_autohex_disable: bool
    outfile_check_timer: int
    wordlist_autohex_disable: bool
    separator: str
    stdout: bool
    show: bool
    left: bool
    username: bool
    remove: bool
    remove_timer: int
    potfile_disable: bool
    potfile: bytes
    encoding_from: CrackEncoding
    encoding_to: CrackEncoding
    debug_mode: int
    logfile_disable: bool
    hccapx_message_pair: int
    nonce_error_corrections: int
    keyboard_layout_mapping: bytes
    benchmark: bool
    benchmark_all: bool
    speed_only: bool
    progress_only: bool
    segment_size: int
    bitmap_min: int
    bitmap_max: int
    cpu_affinity: list[int]
    hook_threads: int
    hash_info: bool
    backend_ignore_cuda: bool
    backend_ignore_hip: bool
    backend_ignore_metal: bool
    backend_ignore_open_cl: bool
    backend_info: bool
    backend_devices: list[int]
    open_cl_device_types: list[int]
    optimized_kernel_enable: bool
    multiply_accel_disabled: bool
    workload_profile: CrackWorkloadProfile
    kernel_accel: int
    kernel_loops: int
    kernel_threads: int
    backend_vector_width: int
    spin_damp: int
    hwmon_disable: bool
    hwmon_temp_abort: int
    scrypt_tmto: int
    skip: int
    limit: int
    keyspace: bool
    rules_file: bytes
    generate_rules: int
    generate_rules_fun_min: int
    generate_rules_fun_max: int
    generate_rules_func_sel: str
    generate_rules_seed: int
    custom_charset1: str
    custom_charset2: str
    custom_charset3: str
    custom_charset4: str
    identify: str
    increment: bool
    increment_min: int
    increment_max: int
    slow_candidates: bool
    brain_server: bool
    brain_server_timer: int
    brain_client: bool
    brain_client_features: str
    brain_host: str
    brain_port: int
    brain_password: str
    brain_session: str
    brain_session_whitelist: str
    def __init__(
        self,
        *,
        attack_mode: CrackAttackMode = ...,
        hash_type: HashType = ...,
        hashes: list[str] = ...,
        quiet: bool = ...,
        hex_charset: bool = ...,
        hex_salt: bool = ...,
        hex_wordlist: bool = ...,
        force: bool = ...,
        deprecated_check_disable: bool = ...,
        status: bool = ...,
        status_json: bool = ...,
        status_timer: int = ...,
        stdin_timeout_abort: int = ...,
        machine_readable: bool = ...,
        keep_guessing: bool = ...,
        self_test_disable: bool = ...,
        loopback: bool = ...,
        markov_hcstat2: bytes = ...,
        markov_disable: bool = ...,
        markov_classic: bool = ...,
        markov_inverse: bool = ...,
        markov_threshold: int = ...,
        runtime: int = ...,
        session: str = ...,
        restore: bool = ...,
        restore_disable: bool = ...,
        restore_file: bytes = ...,
        outfile_format: list[CrackOutfileFormat] = ...,
        outfile_autohex_disable: bool = ...,
        outfile_check_timer: int = ...,
        wordlist_autohex_disable: bool = ...,
        separator: str = ...,
        stdout: bool = ...,
        show: bool = ...,
        left: bool = ...,
        username: bool = ...,
        remove: bool = ...,
        remove_timer: int = ...,
        potfile_disable: bool = ...,
        potfile: bytes = ...,
        encoding_from: CrackEncoding = ...,
        encoding_to: CrackEncoding = ...,
        debug_mode: int = ...,
        logfile_disable: bool = ...,
        hccapx_message_pair: int = ...,
        nonce_error_corrections: int = ...,
        keyboard_layout_mapping: bytes = ...,
        benchmark: bool = ...,
        benchmark_all: bool = ...,
        speed_only: bool = ...,
        progress_only: bool = ...,
        segment_size: int = ...,
        bitmap_min: int = ...,
        bitmap_max: int = ...,
        cpu_affinity: list[int] = ...,
        hook_threads: int = ...,
        hash_info: bool = ...,
        backend_ignore_cuda: bool = ...,
        backend_ignore_hip: bool = ...,
        backend_ignore_metal: bool = ...,
        backend_ignore_open_cl: bool = ...,
        backend_info: bool = ...,
        backend_devices: list[int] = ...,
        open_cl_device_types: list[int] = ...,
        optimized_kernel_enable: bool = ...,
        multiply_accel_disabled: bool = ...,
        workload_profile: CrackWorkloadProfile = ...,
        kernel_accel: int = ...,
        kernel_loops: int = ...,
        kernel_threads: int = ...,
        backend_vector_width: int = ...,
        spin_damp: int = ...,
        hwmon_disable: bool = ...,
        hwmon_temp_abort: int = ...,
        scrypt_tmto: int = ...,
        skip: int = ...,
        limit: int = ...,
        keyspace: bool = ...,
        rules_file: bytes = ...,
        generate_rules: int = ...,
        generate_rules_fun_min: int = ...,
        generate_rules_fun_max: int = ...,
        generate_rules_func_sel: str = ...,
        generate_rules_seed: int = ...,
        custom_charset1: str = ...,
        custom_charset2: str = ...,
        custom_charset3: str = ...,
        custom_charset4: str = ...,
        identify: str = ...,
        increment: bool = ...,
        increment_min: int = ...,
        increment_max: int = ...,
        slow_candidates: bool = ...,
        brain_server: bool = ...,
        brain_server_timer: int = ...,
        brain_client: bool = ...,
        brain_client_features: str = ...,
        brain_host: str = ...,
        brain_port: int = ...,
        brain_password: str = ...,
        brain_session: str = ...,
        brain_session_whitelist: str = ...,
    ) -> None: ...

class CrackJob(ProtobufModel):
    id: str
    created_at: str
    completed_at: str
    status: CrackJobStatus
    err: str
    command: CrackCommand | None
    result_file_id: str
    def __init__(
        self,
        *,
        id: str = ...,
        created_at: str = ...,
        completed_at: str = ...,
        status: CrackJobStatus = ...,
        err: str = ...,
        command: CrackCommand | None = ...,
        result_file_id: str = ...,
    ) -> None: ...

class CrackResponse(ProtobufModel):
    job: CrackJob | None
    def __init__(
        self,
        *,
        job: CrackJob | None = ...,
    ) -> None: ...

class CrackConfig(ProtobufModel):
    auto_fire: bool
    max_file_size: int
    chunk_size: int
    max_disk_usage: int
    def __init__(
        self,
        *,
        auto_fire: bool = ...,
        max_file_size: int = ...,
        chunk_size: int = ...,
        max_disk_usage: int = ...,
    ) -> None: ...

class CrackFiles(ProtobufModel):
    files: list[CrackFile]
    current_disk_usage: int
    max_disk_usage: int
    def __init__(
        self,
        *,
        files: list[CrackFile] = ...,
        current_disk_usage: int = ...,
        max_disk_usage: int = ...,
    ) -> None: ...

class CrackFile(ProtobufModel):
    id: str
    created_at: int
    last_modified: int
    name: str
    uncompressed_size: int
    sha2_256: str
    type: CrackFileType
    is_compressed: bool
    max_file_size: int
    chunk_size: int
    chunks: list[CrackFileChunk]
    def __init__(
        self,
        *,
        id: str = ...,
        created_at: int = ...,
        last_modified: int = ...,
        name: str = ...,
        uncompressed_size: int = ...,
        sha2_256: str = ...,
        type: CrackFileType = ...,
        is_compressed: bool = ...,
        max_file_size: int = ...,
        chunk_size: int = ...,
        chunks: list[CrackFileChunk] = ...,
    ) -> None: ...

class CrackFileChunk(ProtobufModel):
    id: str
    crack_file_id: str
    n: int
    data: bytes
    def __init__(
        self,
        *,
        id: str = ...,
        crack_file_id: str = ...,
        n: int = ...,
        data: bytes = ...,
    ) -> None: ...

class AIProviderConfigs(ProtobufModel):
    providers: list[AIProviderConfig]
    config: AIConfigSummary | None
    def __init__(
        self,
        *,
        providers: list[AIProviderConfig] = ...,
        config: AIConfigSummary | None = ...,
    ) -> None: ...

class AIProviderConfig(ProtobufModel):
    name: str
    configured: bool
    def __init__(
        self,
        *,
        name: str = ...,
        configured: bool = ...,
    ) -> None: ...

class AIConfigSummary(ProtobufModel):
    provider: str
    model: str
    thinking_level: str
    valid: bool
    error: str
    system_prompt: str
    def __init__(
        self,
        *,
        provider: str = ...,
        model: str = ...,
        thinking_level: str = ...,
        valid: bool = ...,
        error: str = ...,
        system_prompt: str = ...,
    ) -> None: ...

class AIConversationReq(ProtobufModel):
    id: str
    include_messages: bool
    def __init__(
        self,
        *,
        id: str = ...,
        include_messages: bool = ...,
    ) -> None: ...

class AIConversations(ProtobufModel):
    conversations: list[AIConversation]
    def __init__(
        self,
        *,
        conversations: list[AIConversation] = ...,
    ) -> None: ...

class AIContextWindowUsage(ProtobufModel):
    input_tokens: int
    output_tokens: int
    total_tokens: int
    context_window_tokens: int
    context_window_tokens_estimated: bool
    def __init__(
        self,
        *,
        input_tokens: int = ...,
        output_tokens: int = ...,
        total_tokens: int = ...,
        context_window_tokens: int = ...,
        context_window_tokens_estimated: bool = ...,
    ) -> None: ...

class AIConversation(ProtobufModel):
    id: str
    created_at: int
    updated_at: int
    operator_name: str
    provider: str
    model: str
    title: str
    summary: str
    system_prompt: str
    messages: list[AIConversationMessage]
    active_turn_id: str
    turn_state: AIConversationTurnState
    target_session_id: str
    target_beacon_id: str
    thinking_level: str
    context_window_usage: AIContextWindowUsage | None
    def __init__(
        self,
        *,
        id: str = ...,
        created_at: int = ...,
        updated_at: int = ...,
        operator_name: str = ...,
        provider: str = ...,
        model: str = ...,
        title: str = ...,
        summary: str = ...,
        system_prompt: str = ...,
        messages: list[AIConversationMessage] = ...,
        active_turn_id: str = ...,
        turn_state: AIConversationTurnState = ...,
        target_session_id: str = ...,
        target_beacon_id: str = ...,
        thinking_level: str = ...,
        context_window_usage: AIContextWindowUsage | None = ...,
    ) -> None: ...

class AIConversationMessages(ProtobufModel):
    conversation_id: str
    messages: list[AIConversationMessage]
    def __init__(
        self,
        *,
        conversation_id: str = ...,
        messages: list[AIConversationMessage] = ...,
    ) -> None: ...

class AIConversationMessage(ProtobufModel):
    id: str
    conversation_id: str
    created_at: int
    updated_at: int
    operator_name: str
    provider: str
    model: str
    sequence: int
    role: str
    content: str
    provider_message_id: str
    finish_reason: str
    kind: AIConversationMessageKind
    visibility: AIConversationMessageVisibility
    state: AIConversationMessageState
    turn_id: str
    item_id: str
    tool_call_id: str
    tool_name: str
    tool_arguments: str
    tool_result: str
    error_text: str
    include_in_context: bool | None
    def __init__(
        self,
        *,
        id: str = ...,
        conversation_id: str = ...,
        created_at: int = ...,
        updated_at: int = ...,
        operator_name: str = ...,
        provider: str = ...,
        model: str = ...,
        sequence: int = ...,
        role: str = ...,
        content: str = ...,
        provider_message_id: str = ...,
        finish_reason: str = ...,
        kind: AIConversationMessageKind = ...,
        visibility: AIConversationMessageVisibility = ...,
        state: AIConversationMessageState = ...,
        turn_id: str = ...,
        item_id: str = ...,
        tool_call_id: str = ...,
        tool_name: str = ...,
        tool_arguments: str = ...,
        tool_result: str = ...,
        error_text: str = ...,
        include_in_context: bool | None = ...,
    ) -> None: ...

class AIConversationEvent(ProtobufModel):
    event_type: AIConversationEventType
    conversation_id: str
    turn_id: str
    error_text: str
    conversation: AIConversation | None
    message: AIConversationMessage | None
    def __init__(
        self,
        *,
        event_type: AIConversationEventType = ...,
        conversation_id: str = ...,
        turn_id: str = ...,
        error_text: str = ...,
        conversation: AIConversation | None = ...,
        message: AIConversationMessage | None = ...,
    ) -> None: ...

class MonitoringProviders(ProtobufModel):
    providers: list[MonitoringProvider]
    def __init__(
        self,
        *,
        providers: list[MonitoringProvider] = ...,
    ) -> None: ...

class MonitoringProvider(ProtobufModel):
    id: str
    type: str
    api_key: str
    api_password: str
    def __init__(
        self,
        *,
        id: str = ...,
        type: str = ...,
        api_key: str = ...,
        api_password: str = ...,
    ) -> None: ...

class ResourceID(ProtobufModel):
    id: str
    type: str
    name: str
    value: int
    def __init__(
        self,
        *,
        id: str = ...,
        type: str = ...,
        name: str = ...,
        value: int = ...,
    ) -> None: ...

class CertificatesReq(ProtobufModel):
    category_filters: int
    cn: str
    def __init__(
        self,
        *,
        category_filters: int = ...,
        cn: str = ...,
    ) -> None: ...

class CertificateData(ProtobufModel):
    cn: str
    creation_time: str
    validity_start: str
    validity_expiry: str
    type: str
    key_algorithm: str
    id: str
    def __init__(
        self,
        *,
        cn: str = ...,
        creation_time: str = ...,
        validity_start: str = ...,
        validity_expiry: str = ...,
        type: str = ...,
        key_algorithm: str = ...,
        id: str = ...,
    ) -> None: ...

class CertificateInfo(ProtobufModel):
    info: list[CertificateData]
    def __init__(
        self,
        *,
        info: list[CertificateData] = ...,
    ) -> None: ...

class CertificateAuthorityData(ProtobufModel):
    cn: str
    creation_time: str
    validity_start: str
    validity_expiry: str
    type: str
    key_algorithm: str
    id: str
    def __init__(
        self,
        *,
        cn: str = ...,
        creation_time: str = ...,
        validity_start: str = ...,
        validity_expiry: str = ...,
        type: str = ...,
        key_algorithm: str = ...,
        id: str = ...,
    ) -> None: ...

class CertificateAuthorityInfo(ProtobufModel):
    info: list[CertificateAuthorityData]
    def __init__(
        self,
        *,
        info: list[CertificateAuthorityData] = ...,
    ) -> None: ...

__all__ = [
    "AIConfigSummary",
    "AIContextWindowUsage",
    "AIConversation",
    "AIConversationEvent",
    "AIConversationEventType",
    "AIConversationMessage",
    "AIConversationMessageKind",
    "AIConversationMessageState",
    "AIConversationMessageVisibility",
    "AIConversationMessages",
    "AIConversationReq",
    "AIConversationTurnState",
    "AIConversations",
    "AIProviderConfig",
    "AIProviderConfigs",
    "AllHosts",
    "AllLoot",
    "Backdoor",
    "BackdoorReq",
    "Beacon",
    "BeaconIntegrity",
    "BeaconTask",
    "BeaconTasks",
    "Beacons",
    "Builder",
    "Builders",
    "C2ProfileReq",
    "CUDABackendInfo",
    "Canaries",
    "CertificateAuthorityData",
    "CertificateAuthorityInfo",
    "CertificateData",
    "CertificateInfo",
    "CertificatesReq",
    "Client",
    "ClientLogData",
    "CloseTunnelReq",
    "Compiler",
    "CompilerTarget",
    "CrackAttackMode",
    "CrackBenchmark",
    "CrackCommand",
    "CrackConfig",
    "CrackEncoding",
    "CrackFile",
    "CrackFileChunk",
    "CrackFileType",
    "CrackFiles",
    "CrackJob",
    "CrackJobStatus",
    "CrackOutfileFormat",
    "CrackResponse",
    "CrackSyncStatus",
    "CrackTask",
    "CrackWorkloadProfile",
    "Crackstation",
    "CrackstationStatus",
    "Crackstations",
    "CreateTunnel",
    "CreateTunnelReq",
    "Credential",
    "Credentials",
    "CrossCompiler",
    "DNSCanary",
    "DNSListenerReq",
    "DeleteReq",
    "DllHijack",
    "DllHijackReq",
    "Event",
    "ExtensionData",
    "ExternalGenerateReq",
    "ExternalImplantBinary",
    "ExternalImplantConfig",
    "FileType",
    "Generate",
    "GenerateReq",
    "GenerateSpoofMetadataReq",
    "GenerateStageReq",
    "GetSystemReq",
    "HTTPC2Config",
    "HTTPC2ConfigReq",
    "HTTPC2Configs",
    "HTTPC2Cookie",
    "HTTPC2Header",
    "HTTPC2ImplantConfig",
    "HTTPC2PathSegment",
    "HTTPC2SegmentType",
    "HTTPC2ServerConfig",
    "HTTPC2URLParameter",
    "HTTPListenerReq",
    "HashType",
    "Host",
    "IMAGE_EXPORT_DIRECTORY",
    "IMAGE_RESOURCE_DATA_ENTRY",
    "IMAGE_RESOURCE_DIRECTORY",
    "IMAGE_RESOURCE_DIRECTORY_ENTRY",
    "IOC",
    "ImplantBuild",
    "ImplantBuilds",
    "ImplantC2",
    "ImplantConfig",
    "ImplantProfile",
    "ImplantProfiles",
    "ImplantStageReq",
    "Job",
    "Jobs",
    "KillJob",
    "KillJobReq",
    "ListenerJob",
    "Loot",
    "MSFRemoteReq",
    "MSFReq",
    "MTLSListenerReq",
    "MetalBackendInfo",
    "MigrateReq",
    "MonitoringProvider",
    "MonitoringProviders",
    "MultiplayerListenerReq",
    "NamedPipes",
    "NamedPipesReq",
    "OpenCLBackendInfo",
    "Operator",
    "Operators",
    "OutputFormat",
    "PESpoofMetadataConfig",
    "PivotGraph",
    "PivotGraphEntry",
    "RegenerateReq",
    "RenameReq",
    "ResourceID",
    "RestartJobReq",
    "Session",
    "Sessions",
    "ShellcodeConfig",
    "ShellcodeEncode",
    "ShellcodeEncodeReq",
    "ShellcodeEncoder",
    "ShellcodeEncoderArchMap",
    "ShellcodeEncoderMap",
    "ShellcodeRDI",
    "ShellcodeRDIReq",
    "SpoofMetadataConfig",
    "SpoofMetadataFile",
    "StageProtocol",
    "StagerListener",
    "StagerListenerReq",
    "States",
    "TCPPivot",
    "TCPPivotReq",
    "TrafficEncoder",
    "TrafficEncoderMap",
    "TrafficEncoderTest",
    "TrafficEncoderTests",
    "UniqueWGIP",
    "Version",
    "WGClientConfig",
    "WGListenerReq",
    "WebContent",
    "Website",
    "WebsiteAddContent",
    "WebsiteRemoveContent",
    "Websites",
]
