# @generated by scripts/pydanticgen.py; DO NOT EDIT.
"""Concrete Pydantic models for Sliver package ``commonpb``."""

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from ._runtime import (
    ProtobufModel,
    _protobuf_field,
    _register_model,
)


@_register_model("commonpb.Empty")
class Empty(ProtobufModel):
    """Pydantic model for ``commonpb.Empty``."""

    pass


@_register_model("commonpb.Request")
class Request(ProtobufModel):
    """Pydantic model for ``commonpb.Request``."""

    async_: bool = _protobuf_field(
        "Async", "Async", "commonpb.Request.Async", 1, default=False
    )
    timeout: Annotated[int, Field(ge=-9223372036854775808, le=9223372036854775807)] = (
        _protobuf_field("Timeout", "Timeout", "commonpb.Request.Timeout", 2, default=0)
    )
    beacon_id: str = _protobuf_field(
        "BeaconID", "BeaconID", "commonpb.Request.BeaconID", 8, default=""
    )
    session_id: str = _protobuf_field(
        "SessionID", "SessionID", "commonpb.Request.SessionID", 9, default=""
    )


@_register_model("commonpb.Response")
class Response(ProtobufModel):
    """Pydantic model for ``commonpb.Response``."""

    err: str = _protobuf_field("Err", "Err", "commonpb.Response.Err", 1, default="")
    async_: bool = _protobuf_field(
        "Async", "Async", "commonpb.Response.Async", 2, default=False
    )
    beacon_id: str = _protobuf_field(
        "BeaconID", "BeaconID", "commonpb.Response.BeaconID", 8, default=""
    )
    task_id: str = _protobuf_field(
        "TaskID", "TaskID", "commonpb.Response.TaskID", 9, default=""
    )


@_register_model("commonpb.File")
class File(ProtobufModel):
    """Pydantic model for ``commonpb.File``."""

    name: str = _protobuf_field("Name", "Name", "commonpb.File.Name", 1, default="")
    data: bytes = _protobuf_field("Data", "Data", "commonpb.File.Data", 2, default=b"")


@_register_model("commonpb.Process")
class Process(ProtobufModel):
    """Pydantic model for ``commonpb.Process``."""

    pid: Annotated[int, Field(ge=-2147483648, le=2147483647)] = _protobuf_field(
        "Pid", "Pid", "commonpb.Process.Pid", 1, default=0
    )
    ppid: Annotated[int, Field(ge=-2147483648, le=2147483647)] = _protobuf_field(
        "Ppid", "Ppid", "commonpb.Process.Ppid", 2, default=0
    )
    executable: str = _protobuf_field(
        "Executable", "Executable", "commonpb.Process.Executable", 3, default=""
    )
    owner: str = _protobuf_field(
        "Owner", "Owner", "commonpb.Process.Owner", 4, default=""
    )
    architecture: str = _protobuf_field(
        "Architecture", "Architecture", "commonpb.Process.Architecture", 7, default=""
    )
    session_id: Annotated[int, Field(ge=-2147483648, le=2147483647)] = _protobuf_field(
        "SessionID", "SessionID", "commonpb.Process.SessionID", 5, default=0
    )
    cmd_line: list[str] = _protobuf_field(
        "CmdLine", "CmdLine", "commonpb.Process.CmdLine", 6, default_factory=list
    )


@_register_model("commonpb.EnvVar")
class EnvVar(ProtobufModel):
    """Pydantic model for ``commonpb.EnvVar``."""

    key: str = _protobuf_field("Key", "Key", "commonpb.EnvVar.Key", 1, default="")
    value: str = _protobuf_field(
        "Value", "Value", "commonpb.EnvVar.Value", 2, default=""
    )


__all__ = [
    "Empty",
    "EnvVar",
    "File",
    "Process",
    "Request",
    "Response",
]
