# @generated by scripts/pydanticgen.py; DO NOT EDIT.
"""Static types for the concrete models in ``commonpb``."""

from __future__ import annotations

from ._runtime import ProtobufModel

class Empty(ProtobufModel):
    def __init__(self) -> None: ...

class Request(ProtobufModel):
    async_: bool
    timeout: int
    beacon_id: str
    session_id: str
    def __init__(
        self,
        *,
        async_: bool = ...,
        timeout: int = ...,
        beacon_id: str = ...,
        session_id: str = ...,
    ) -> None: ...

class Response(ProtobufModel):
    err: str
    async_: bool
    beacon_id: str
    task_id: str
    def __init__(
        self,
        *,
        err: str = ...,
        async_: bool = ...,
        beacon_id: str = ...,
        task_id: str = ...,
    ) -> None: ...

class File(ProtobufModel):
    name: str
    data: bytes
    def __init__(
        self,
        *,
        name: str = ...,
        data: bytes = ...,
    ) -> None: ...

class Process(ProtobufModel):
    pid: int
    ppid: int
    executable: str
    owner: str
    architecture: str
    session_id: int
    cmd_line: list[str]
    def __init__(
        self,
        *,
        pid: int = ...,
        ppid: int = ...,
        executable: str = ...,
        owner: str = ...,
        architecture: str = ...,
        session_id: int = ...,
        cmd_line: list[str] = ...,
    ) -> None: ...

class EnvVar(ProtobufModel):
    key: str
    value: str
    def __init__(
        self,
        *,
        key: str = ...,
        value: str = ...,
    ) -> None: ...

__all__ = [
    "Empty",
    "EnvVar",
    "File",
    "Process",
    "Request",
    "Response",
]
