# @generated by scripts/pydanticgen.py; DO NOT EDIT.
"""Static types for the concrete models in ``sliverpb``."""

from __future__ import annotations

from typing import TypeAlias

from . import commonpb as commonpb
from ._runtime import (
    ProtobufEnum,
    ProtobufModel,
)

class ImplantCapability(ProtobufEnum):
    IMPLANT_CAPABILITY_NONE: ImplantCapability
    IMPLANT_CAPABILITY_BOF_V1: ImplantCapability

class RegistryType(ProtobufEnum):
    Unknown: RegistryType
    Binary: RegistryType
    String: RegistryType
    DWORD: RegistryType
    QWORD: RegistryType

class PivotType(ProtobufEnum):
    TCP: PivotType
    UDP: PivotType
    NamedPipe: PivotType

class PeerFailureType(ProtobufEnum):
    SEND_FAILURE: PeerFailureType
    DISCONNECT: PeerFailureType

class Envelope(ProtobufModel):
    id: int
    type: int
    data: bytes
    unknown_message_type: bool
    def __init__(
        self,
        *,
        id: int = ...,
        type: int = ...,
        data: bytes = ...,
        unknown_message_type: bool = ...,
    ) -> None: ...

class BeaconTasks(ProtobufModel):
    id: str
    tasks: list[Envelope]
    next_checkin: int
    def __init__(
        self,
        *,
        id: str = ...,
        tasks: list[Envelope] = ...,
        next_checkin: int = ...,
    ) -> None: ...

class Register(ProtobufModel):
    name: str
    hostname: str
    uuid: str
    username: str
    uid: str
    gid: str
    os: str
    arch: str
    pid: int
    filename: str
    active_c2: str
    version: str
    reconnect_interval: int
    proxy_url: str
    config_id: str
    peer_id: int
    locale: str
    capabilities: int
    def __init__(
        self,
        *,
        name: str = ...,
        hostname: str = ...,
        uuid: str = ...,
        username: str = ...,
        uid: str = ...,
        gid: str = ...,
        os: str = ...,
        arch: str = ...,
        pid: int = ...,
        filename: str = ...,
        active_c2: str = ...,
        version: str = ...,
        reconnect_interval: int = ...,
        proxy_url: str = ...,
        config_id: str = ...,
        peer_id: int = ...,
        locale: str = ...,
        capabilities: int = ...,
    ) -> None: ...

class BeaconRegister(ProtobufModel):
    id: str
    interval: int
    jitter: int
    register_: Register | None
    next_checkin: int
    def __init__(
        self,
        *,
        id: str = ...,
        interval: int = ...,
        jitter: int = ...,
        register_: Register | None = ...,
        next_checkin: int = ...,
    ) -> None: ...

class SessionRegister(ProtobufModel):
    id: str
    register_: Register | None
    def __init__(
        self,
        *,
        id: str = ...,
        register_: Register | None = ...,
    ) -> None: ...

class OpenSession(ProtobufModel):
    c2s: list[str]
    delay: int
    response: commonpb.Response | None
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        c2s: list[str] = ...,
        delay: int = ...,
        response: commonpb.Response | None = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class CloseSession(ProtobufModel):
    response: commonpb.Response | None
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Ping(ProtobufModel):
    nonce: int
    response: commonpb.Response | None
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        nonce: int = ...,
        response: commonpb.Response | None = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class KillReq(ProtobufModel):
    force: bool
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        force: bool = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class PsReq(ProtobufModel):
    full_info: bool
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        full_info: bool = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Ps(ProtobufModel):
    processes: list[commonpb.Process]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        processes: list[commonpb.Process] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class TerminateReq(ProtobufModel):
    pid: int
    force: bool
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        pid: int = ...,
        force: bool = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Terminate(ProtobufModel):
    pid: int
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        pid: int = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class IfconfigReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Ifconfig(ProtobufModel):
    net_interfaces: list[NetInterface]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        net_interfaces: list[NetInterface] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class NetInterface(ProtobufModel):
    index: int
    name: str
    mac: str
    ip_addresses: list[str]
    def __init__(
        self,
        *,
        index: int = ...,
        name: str = ...,
        mac: str = ...,
        ip_addresses: list[str] = ...,
    ) -> None: ...

class LsReq(ProtobufModel):
    path: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        path: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Ls(ProtobufModel):
    path: str
    exists: bool
    files: list[FileInfo]
    timezone: str
    timezone_offset: int
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        path: str = ...,
        exists: bool = ...,
        files: list[FileInfo] = ...,
        timezone: str = ...,
        timezone_offset: int = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class FileInfo(ProtobufModel):
    name: str
    is_dir: bool
    size: int
    mod_time: int
    mode: str
    link: str
    uid: str
    gid: str
    def __init__(
        self,
        *,
        name: str = ...,
        is_dir: bool = ...,
        size: int = ...,
        mod_time: int = ...,
        mode: str = ...,
        link: str = ...,
        uid: str = ...,
        gid: str = ...,
    ) -> None: ...

class CdReq(ProtobufModel):
    path: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        path: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class PwdReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Pwd(ProtobufModel):
    path: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        path: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RmReq(ProtobufModel):
    path: str
    recursive: bool
    force: bool
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        path: str = ...,
        recursive: bool = ...,
        force: bool = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Rm(ProtobufModel):
    path: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        path: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class MvReq(ProtobufModel):
    src: str
    dst: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        src: str = ...,
        dst: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Mv(ProtobufModel):
    src: str
    dst: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        src: str = ...,
        dst: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class CpReq(ProtobufModel):
    src: str
    dst: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        src: str = ...,
        dst: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Cp(ProtobufModel):
    src: str
    dst: str
    bytes_written: int
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        src: str = ...,
        dst: str = ...,
        bytes_written: int = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class MkdirReq(ProtobufModel):
    path: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        path: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Mkdir(ProtobufModel):
    path: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        path: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class DownloadReq(ProtobufModel):
    path: str
    start: int
    stop: int
    recurse: bool
    max_bytes: int
    max_lines: int
    restricted_to_file: bool
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        path: str = ...,
        start: int = ...,
        stop: int = ...,
        recurse: bool = ...,
        max_bytes: int = ...,
        max_lines: int = ...,
        restricted_to_file: bool = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Download(ProtobufModel):
    path: str
    encoder: str
    exists: bool
    start: int
    stop: int
    data: bytes
    is_dir: bool
    read_files: int
    unreadable_files: int
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        path: str = ...,
        encoder: str = ...,
        exists: bool = ...,
        start: int = ...,
        stop: int = ...,
        data: bytes = ...,
        is_dir: bool = ...,
        read_files: int = ...,
        unreadable_files: int = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class UploadReq(ProtobufModel):
    path: str
    encoder: str
    data: bytes
    is_ioc: bool
    file_name: str
    is_directory: bool
    overwrite: bool
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        path: str = ...,
        encoder: str = ...,
        data: bytes = ...,
        is_ioc: bool = ...,
        file_name: str = ...,
        is_directory: bool = ...,
        overwrite: bool = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Upload(ProtobufModel):
    path: str
    written_files: int
    unwriteable_files: int
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        path: str = ...,
        written_files: int = ...,
        unwriteable_files: int = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class GrepReq(ProtobufModel):
    search_pattern: str
    path: str
    recursive: bool
    lines_before: int
    lines_after: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        search_pattern: str = ...,
        path: str = ...,
        recursive: bool = ...,
        lines_before: int = ...,
        lines_after: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class GrepLinePosition(ProtobufModel):
    start: int
    end: int
    def __init__(
        self,
        *,
        start: int = ...,
        end: int = ...,
    ) -> None: ...

class GrepResult(ProtobufModel):
    line_number: int
    positions: list[GrepLinePosition]
    line: str
    lines_before: list[str]
    lines_after: list[str]
    def __init__(
        self,
        *,
        line_number: int = ...,
        positions: list[GrepLinePosition] = ...,
        line: str = ...,
        lines_before: list[str] = ...,
        lines_after: list[str] = ...,
    ) -> None: ...

class GrepResultsForFile(ProtobufModel):
    file_results: list[GrepResult]
    is_binary: bool
    def __init__(
        self,
        *,
        file_results: list[GrepResult] = ...,
        is_binary: bool = ...,
    ) -> None: ...

class Grep(ProtobufModel):
    results: dict[str, GrepResultsForFile]
    search_path_absolute: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        results: dict[str, GrepResultsForFile] = ...,
        search_path_absolute: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class MountReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class MountInfo(ProtobufModel):
    volume_name: str
    volume_type: str
    mount_point: str
    label: str
    file_system: str
    used_space: int
    free_space: int
    total_space: int
    mount_options: str
    def __init__(
        self,
        *,
        volume_name: str = ...,
        volume_type: str = ...,
        mount_point: str = ...,
        label: str = ...,
        file_system: str = ...,
        used_space: int = ...,
        free_space: int = ...,
        total_space: int = ...,
        mount_options: str = ...,
    ) -> None: ...

class Mount(ProtobufModel):
    info: list[MountInfo]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        info: list[MountInfo] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ProcessDumpReq(ProtobufModel):
    pid: int
    timeout: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        pid: int = ...,
        timeout: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class ProcessDump(ProtobufModel):
    data: bytes
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        data: bytes = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RunAsReq(ProtobufModel):
    username: str
    process_name: str
    args: str
    domain: str
    password: str
    hide_window: bool
    net_only: bool
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        username: str = ...,
        process_name: str = ...,
        args: str = ...,
        domain: str = ...,
        password: str = ...,
        hide_window: bool = ...,
        net_only: bool = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RunAs(ProtobufModel):
    output: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        output: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ImpersonateReq(ProtobufModel):
    username: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        username: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Impersonate(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RevToSelfReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RevToSelf(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class CurrentTokenOwnerReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class CurrentTokenOwner(ProtobufModel):
    output: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        output: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class InvokeGetSystemReq(ProtobufModel):
    data: bytes
    hosting_process: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        data: bytes = ...,
        hosting_process: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class GetSystem(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class MakeTokenReq(ProtobufModel):
    username: str
    password: str
    domain: str
    logon_type: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        username: str = ...,
        password: str = ...,
        domain: str = ...,
        logon_type: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class MakeToken(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class TaskReq(ProtobufModel):
    encoder: str
    rwx_pages: bool
    pid: int
    data: bytes
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        encoder: str = ...,
        rwx_pages: bool = ...,
        pid: int = ...,
        data: bytes = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Task(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ExecuteAssemblyReq(ProtobufModel):
    assembly: bytes
    arguments: list[str]
    process: str
    is_dll: bool
    arch: str
    class_name: str
    method: str
    app_domain: str
    p_pid: int
    process_args: list[str]
    in_process: bool
    runtime: str
    amsi_bypass: bool
    etw_bypass: bool
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        assembly: bytes = ...,
        arguments: list[str] = ...,
        process: str = ...,
        is_dll: bool = ...,
        arch: str = ...,
        class_name: str = ...,
        method: str = ...,
        app_domain: str = ...,
        p_pid: int = ...,
        process_args: list[str] = ...,
        in_process: bool = ...,
        runtime: str = ...,
        amsi_bypass: bool = ...,
        etw_bypass: bool = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class InvokeExecuteAssemblyReq(ProtobufModel):
    data: bytes
    process: str
    p_pid: int
    process_args: list[str]
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        data: bytes = ...,
        process: str = ...,
        p_pid: int = ...,
        process_args: list[str] = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class InvokeInProcExecuteAssemblyReq(ProtobufModel):
    data: bytes
    arguments: list[str]
    runtime: str
    amsi_bypass: bool
    etw_bypass: bool
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        data: bytes = ...,
        arguments: list[str] = ...,
        runtime: str = ...,
        amsi_bypass: bool = ...,
        etw_bypass: bool = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class ExecuteAssembly(ProtobufModel):
    output: bytes
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        output: bytes = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class InvokeMigrateReq(ProtobufModel):
    pid: int
    data: bytes
    proc_name: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        pid: int = ...,
        data: bytes = ...,
        proc_name: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Migrate(ProtobufModel):
    success: bool
    pid: int
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        success: bool = ...,
        pid: int = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ExecuteReq(ProtobufModel):
    path: str
    args: list[str]
    output: bool
    stdout: str
    stderr: str
    env_inheritance: bool
    env: dict[str, str]
    background: bool
    p_pid: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        path: str = ...,
        args: list[str] = ...,
        output: bool = ...,
        stdout: str = ...,
        stderr: str = ...,
        env_inheritance: bool = ...,
        env: dict[str, str] = ...,
        background: bool = ...,
        p_pid: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class ExecuteWindowsReq(ProtobufModel):
    path: str
    args: list[str]
    output: bool
    stdout: str
    stderr: str
    use_token: bool
    hide_window: bool
    background: bool
    p_pid: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        path: str = ...,
        args: list[str] = ...,
        output: bool = ...,
        stdout: str = ...,
        stderr: str = ...,
        use_token: bool = ...,
        hide_window: bool = ...,
        background: bool = ...,
        p_pid: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Execute(ProtobufModel):
    status: int
    stdout: bytes
    stderr: bytes
    pid: int
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        status: int = ...,
        stdout: bytes = ...,
        stderr: bytes = ...,
        pid: int = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ExecuteChildrenReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class ExecuteChild(ProtobufModel):
    pid: int
    path: str
    args: list[str]
    start_time: int
    exited: bool
    exit_code: int
    exit_time: int
    stdout: str
    stderr: str
    error: str
    def __init__(
        self,
        *,
        pid: int = ...,
        path: str = ...,
        args: list[str] = ...,
        start_time: int = ...,
        exited: bool = ...,
        exit_code: int = ...,
        exit_time: int = ...,
        stdout: str = ...,
        stderr: str = ...,
        error: str = ...,
    ) -> None: ...

class ExecuteChildren(ProtobufModel):
    children: list[ExecuteChild]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        children: list[ExecuteChild] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class SideloadReq(ProtobufModel):
    data: bytes
    process_name: str
    args: list[str]
    entry_point: str
    kill: bool
    is_dll: bool
    is_unicode: bool
    p_pid: int
    process_args: list[str]
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        data: bytes = ...,
        process_name: str = ...,
        args: list[str] = ...,
        entry_point: str = ...,
        kill: bool = ...,
        is_dll: bool = ...,
        is_unicode: bool = ...,
        p_pid: int = ...,
        process_args: list[str] = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Sideload(ProtobufModel):
    result: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        result: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class InvokeSpawnDllReq(ProtobufModel):
    data: bytes
    process_name: str
    args: list[str]
    entry_point: str
    kill: bool
    p_pid: int
    process_args: list[str]
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        data: bytes = ...,
        process_name: str = ...,
        args: list[str] = ...,
        entry_point: str = ...,
        kill: bool = ...,
        p_pid: int = ...,
        process_args: list[str] = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class SpawnDllReq(ProtobufModel):
    data: bytes
    process_name: str
    offset: int
    args: list[str]
    kill: bool
    p_pid: int
    process_args: list[str]
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        data: bytes = ...,
        process_name: str = ...,
        offset: int = ...,
        args: list[str] = ...,
        kill: bool = ...,
        p_pid: int = ...,
        process_args: list[str] = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class SpawnDll(ProtobufModel):
    result: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        result: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class NetstatReq(ProtobufModel):
    tcp: bool
    udp: bool
    ip4: bool
    ip6: bool
    listening: bool
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        tcp: bool = ...,
        udp: bool = ...,
        ip4: bool = ...,
        ip6: bool = ...,
        listening: bool = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class _SockTabEntry_SockAddr(ProtobufModel):
    ip: str
    port: int
    def __init__(
        self,
        *,
        ip: str = ...,
        port: int = ...,
    ) -> None: ...

class SockTabEntry(ProtobufModel):
    SockAddr: TypeAlias = _SockTabEntry_SockAddr
    local_addr: _SockTabEntry_SockAddr | None
    remote_addr: _SockTabEntry_SockAddr | None
    sk_state: str
    uid: int
    process: commonpb.Process | None
    protocol: str
    def __init__(
        self,
        *,
        local_addr: _SockTabEntry_SockAddr | None = ...,
        remote_addr: _SockTabEntry_SockAddr | None = ...,
        sk_state: str = ...,
        uid: int = ...,
        process: commonpb.Process | None = ...,
        protocol: str = ...,
    ) -> None: ...

class Netstat(ProtobufModel):
    entries: list[SockTabEntry]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        entries: list[SockTabEntry] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class EnvReq(ProtobufModel):
    name: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        name: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class EnvInfo(ProtobufModel):
    variables: list[commonpb.EnvVar]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        variables: list[commonpb.EnvVar] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class SetEnvReq(ProtobufModel):
    variable: commonpb.EnvVar | None
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        variable: commonpb.EnvVar | None = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class SetEnv(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class UnsetEnvReq(ProtobufModel):
    name: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        name: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class UnsetEnv(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class HTTPSessionInit(ProtobufModel):
    key: bytes
    def __init__(
        self,
        *,
        key: bytes = ...,
    ) -> None: ...

class ScreenshotReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Screenshot(ProtobufModel):
    data: bytes
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        data: bytes = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class StartServiceReq(ProtobufModel):
    service_name: str
    service_description: str
    bin_path: str
    hostname: str
    arguments: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        service_name: str = ...,
        service_description: str = ...,
        bin_path: str = ...,
        hostname: str = ...,
        arguments: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class ServiceInfo(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ServiceInfoReq(ProtobufModel):
    service_name: str
    hostname: str
    def __init__(
        self,
        *,
        service_name: str = ...,
        hostname: str = ...,
    ) -> None: ...

class StopServiceReq(ProtobufModel):
    service_info: ServiceInfoReq | None
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        service_info: ServiceInfoReq | None = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RemoveServiceReq(ProtobufModel):
    service_info: ServiceInfoReq | None
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        service_info: ServiceInfoReq | None = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RegistryReadReq(ProtobufModel):
    hive: str
    path: str
    key: str
    hostname: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        hive: str = ...,
        path: str = ...,
        key: str = ...,
        hostname: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RegistryRead(ProtobufModel):
    value: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        value: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RegistryWriteReq(ProtobufModel):
    hive: str
    path: str
    key: str
    hostname: str
    string_value: str
    byte_value: bytes
    d_word_value: int
    q_word_value: int
    type: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        hive: str = ...,
        path: str = ...,
        key: str = ...,
        hostname: str = ...,
        string_value: str = ...,
        byte_value: bytes = ...,
        d_word_value: int = ...,
        q_word_value: int = ...,
        type: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RegistryWrite(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RegistryCreateKeyReq(ProtobufModel):
    hive: str
    path: str
    key: str
    hostname: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        hive: str = ...,
        path: str = ...,
        key: str = ...,
        hostname: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RegistryCreateKey(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RegistryDeleteKeyReq(ProtobufModel):
    hive: str
    path: str
    key: str
    hostname: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        hive: str = ...,
        path: str = ...,
        key: str = ...,
        hostname: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RegistryDeleteKey(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RegistrySubKeyListReq(ProtobufModel):
    hive: str
    path: str
    hostname: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        hive: str = ...,
        path: str = ...,
        hostname: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RegistrySubKeyList(ProtobufModel):
    subkeys: list[str]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        subkeys: list[str] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RegistryListValuesReq(ProtobufModel):
    hive: str
    path: str
    hostname: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        hive: str = ...,
        path: str = ...,
        hostname: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RegistryValuesList(ProtobufModel):
    value_names: list[str]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        value_names: list[str] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RegistryReadHiveReq(ProtobufModel):
    root_hive: str
    requested_hive: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        root_hive: str = ...,
        requested_hive: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RegistryReadHive(ProtobufModel):
    data: bytes
    encoder: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        data: bytes = ...,
        encoder: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class Tunnel(ProtobufModel):
    tunnel_id: int
    session_id: str
    def __init__(
        self,
        *,
        tunnel_id: int = ...,
        session_id: str = ...,
    ) -> None: ...

class TunnelData(ProtobufModel):
    data: bytes
    closed: bool
    sequence: int
    ack: int
    resend: bool
    create_reverse: bool
    rportfwd: RPortfwd | None
    tunnel_id: int
    session_id: str
    def __init__(
        self,
        *,
        data: bytes = ...,
        closed: bool = ...,
        sequence: int = ...,
        ack: int = ...,
        resend: bool = ...,
        create_reverse: bool = ...,
        rportfwd: RPortfwd | None = ...,
        tunnel_id: int = ...,
        session_id: str = ...,
    ) -> None: ...

class ShellReq(ProtobufModel):
    path: str
    enable_pty: bool
    pid: int
    rows: int
    cols: int
    tunnel_id: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        path: str = ...,
        enable_pty: bool = ...,
        pid: int = ...,
        rows: int = ...,
        cols: int = ...,
        tunnel_id: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Shell(ProtobufModel):
    path: str
    enable_pty: bool
    pid: int
    tunnel_id: int
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        path: str = ...,
        enable_pty: bool = ...,
        pid: int = ...,
        tunnel_id: int = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ShellResizeReq(ProtobufModel):
    rows: int
    cols: int
    tunnel_id: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        rows: int = ...,
        cols: int = ...,
        tunnel_id: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class PortfwdReq(ProtobufModel):
    port: int
    protocol: int
    host: str
    keep_alive: int
    tunnel_id: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        port: int = ...,
        protocol: int = ...,
        host: str = ...,
        keep_alive: int = ...,
        tunnel_id: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Portfwd(ProtobufModel):
    port: int
    protocol: int
    host: str
    tunnel_id: int
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        port: int = ...,
        protocol: int = ...,
        host: str = ...,
        tunnel_id: int = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class Socks(ProtobufModel):
    tunnel_id: int
    session_id: str
    def __init__(
        self,
        *,
        tunnel_id: int = ...,
        session_id: str = ...,
    ) -> None: ...

class SocksData(ProtobufModel):
    data: bytes
    close_conn: bool
    username: str
    password: str
    sequence: int
    tunnel_id: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        data: bytes = ...,
        close_conn: bool = ...,
        username: str = ...,
        password: str = ...,
        sequence: int = ...,
        tunnel_id: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class PivotStartListenerReq(ProtobufModel):
    type: PivotType
    bind_address: str
    options: list[bool]
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        type: PivotType = ...,
        bind_address: str = ...,
        options: list[bool] = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class PivotStopListenerReq(ProtobufModel):
    id: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        id: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class PivotListener(ProtobufModel):
    id: int
    type: PivotType
    bind_address: str
    pivots: list[NetConnPivot]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        id: int = ...,
        type: PivotType = ...,
        bind_address: str = ...,
        pivots: list[NetConnPivot] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class PivotHello(ProtobufModel):
    public_key: bytes
    peer_id: int
    public_key_signature: str
    session_key: bytes
    def __init__(
        self,
        *,
        public_key: bytes = ...,
        peer_id: int = ...,
        public_key_signature: str = ...,
        session_key: bytes = ...,
    ) -> None: ...

class PivotServerKeyExchange(ProtobufModel):
    origin_id: int
    session_key: bytes
    def __init__(
        self,
        *,
        origin_id: int = ...,
        session_key: bytes = ...,
    ) -> None: ...

class PivotPeer(ProtobufModel):
    peer_id: int
    name: str
    def __init__(
        self,
        *,
        peer_id: int = ...,
        name: str = ...,
    ) -> None: ...

class PivotPeerEnvelope(ProtobufModel):
    peers: list[PivotPeer]
    type: int
    pivot_session_id: bytes
    data: bytes
    peer_failure_at: int
    def __init__(
        self,
        *,
        peers: list[PivotPeer] = ...,
        type: int = ...,
        pivot_session_id: bytes = ...,
        data: bytes = ...,
        peer_failure_at: int = ...,
    ) -> None: ...

class PivotPing(ProtobufModel):
    nonce: int
    def __init__(
        self,
        *,
        nonce: int = ...,
    ) -> None: ...

class NetConnPivot(ProtobufModel):
    peer_id: int
    remote_address: str
    def __init__(
        self,
        *,
        peer_id: int = ...,
        remote_address: str = ...,
    ) -> None: ...

class PivotPeerFailure(ProtobufModel):
    peer_id: int
    type: PeerFailureType
    err: str
    def __init__(
        self,
        *,
        peer_id: int = ...,
        type: PeerFailureType = ...,
        err: str = ...,
    ) -> None: ...

class PivotListenersReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class PivotListeners(ProtobufModel):
    listeners: list[PivotListener]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        listeners: list[PivotListener] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class WGPortForwardStartReq(ProtobufModel):
    local_port: int
    remote_address: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        local_port: int = ...,
        remote_address: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class WGPortForward(ProtobufModel):
    forwarder: WGTCPForwarder | None
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        forwarder: WGTCPForwarder | None = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class WGPortForwardStopReq(ProtobufModel):
    id: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        id: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class WGSocksStartReq(ProtobufModel):
    port: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        port: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class WGSocks(ProtobufModel):
    server: WGSocksServer | None
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        server: WGSocksServer | None = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class WGSocksStopReq(ProtobufModel):
    id: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        id: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class WGTCPForwardersReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class WGSocksServersReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class WGTCPForwarder(ProtobufModel):
    id: int
    local_addr: str
    remote_addr: str
    def __init__(
        self,
        *,
        id: int = ...,
        local_addr: str = ...,
        remote_addr: str = ...,
    ) -> None: ...

class WGSocksServer(ProtobufModel):
    id: int
    local_addr: str
    def __init__(
        self,
        *,
        id: int = ...,
        local_addr: str = ...,
    ) -> None: ...

class WGSocksServers(ProtobufModel):
    servers: list[WGSocksServer]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        servers: list[WGSocksServer] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class WGTCPForwarders(ProtobufModel):
    forwarders: list[WGTCPForwarder]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        forwarders: list[WGTCPForwarder] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ReconfigureReq(ProtobufModel):
    reconnect_interval: int
    beacon_interval: int
    beacon_jitter: int
    c2_uri: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        reconnect_interval: int = ...,
        beacon_interval: int = ...,
        beacon_jitter: int = ...,
        c2_uri: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Reconfigure(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class PollIntervalReq(ProtobufModel):
    poll_interval: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        poll_interval: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class PollInterval(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class SSHCommandReq(ProtobufModel):
    username: str
    hostname: str
    port: int
    command: str
    password: str
    priv_key: bytes
    krb5_conf: str
    keytab: bytes
    realm: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        username: str = ...,
        hostname: str = ...,
        port: int = ...,
        command: str = ...,
        password: str = ...,
        priv_key: bytes = ...,
        krb5_conf: str = ...,
        keytab: bytes = ...,
        realm: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class SSHCommand(ProtobufModel):
    std_out: str
    std_err: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        std_out: str = ...,
        std_err: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class GetPrivsReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class WindowsPrivilegeEntry(ProtobufModel):
    name: str
    description: str
    enabled: bool
    enabled_by_default: bool
    removed: bool
    used_for_access: bool
    def __init__(
        self,
        *,
        name: str = ...,
        description: str = ...,
        enabled: bool = ...,
        enabled_by_default: bool = ...,
        removed: bool = ...,
        used_for_access: bool = ...,
    ) -> None: ...

class GetPrivs(ProtobufModel):
    priv_info: list[WindowsPrivilegeEntry]
    process_integrity: str
    process_name: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        priv_info: list[WindowsPrivilegeEntry] = ...,
        process_integrity: str = ...,
        process_name: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RegisterExtensionReq(ProtobufModel):
    name: str
    data: bytes
    os: str
    init: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        name: str = ...,
        data: bytes = ...,
        os: str = ...,
        init: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RegisterExtension(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class CallExtensionReq(ProtobufModel):
    name: str
    server_store: bool
    args: bytes
    export: str
    bof_data: bytes
    is_bof: bool
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        name: str = ...,
        server_store: bool = ...,
        args: bytes = ...,
        export: str = ...,
        bof_data: bytes = ...,
        is_bof: bool = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class CallExtension(ProtobufModel):
    output: bytes
    server_store: bool
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        output: bytes = ...,
        server_store: bool = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ListExtensionsReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class ListExtensions(ProtobufModel):
    names: list[str]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        names: list[str] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RportFwdStopListenerReq(ProtobufModel):
    id: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        id: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RportFwdStartListenerReq(ProtobufModel):
    bind_address: str
    bind_port: int
    forward_port: int
    forward_address: str
    keep_alive: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        bind_address: str = ...,
        bind_port: int = ...,
        forward_port: int = ...,
        forward_address: str = ...,
        keep_alive: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RportFwdListener(ProtobufModel):
    id: int
    bind_address: str
    bind_port: int
    forward_address: str
    forward_port: int
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        id: int = ...,
        bind_address: str = ...,
        bind_port: int = ...,
        forward_address: str = ...,
        forward_port: int = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RportFwdListeners(ProtobufModel):
    listeners: list[RportFwdListener]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        listeners: list[RportFwdListener] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RportFwdListenersReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RPortfwd(ProtobufModel):
    port: int
    protocol: int
    host: str
    tunnel_id: int
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        port: int = ...,
        protocol: int = ...,
        host: str = ...,
        tunnel_id: int = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RPortfwdReq(ProtobufModel):
    port: int
    protocol: int
    host: str
    tunnel_id: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        port: int = ...,
        protocol: int = ...,
        host: str = ...,
        tunnel_id: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class ChmodReq(ProtobufModel):
    path: str
    file_mode: str
    recursive: bool
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        path: str = ...,
        file_mode: str = ...,
        recursive: bool = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Chmod(ProtobufModel):
    path: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        path: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ChownReq(ProtobufModel):
    path: str
    uid: str
    gid: str
    recursive: bool
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        path: str = ...,
        uid: str = ...,
        gid: str = ...,
        recursive: bool = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Chown(ProtobufModel):
    path: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        path: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ChtimesReq(ProtobufModel):
    path: str
    a_time: int
    m_time: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        path: str = ...,
        a_time: int = ...,
        m_time: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class Chtimes(ProtobufModel):
    path: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        path: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class MemfilesListReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class MemfilesAddReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class MemfilesAdd(ProtobufModel):
    fd: int
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        fd: int = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class MemfilesRmReq(ProtobufModel):
    fd: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        fd: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class MemfilesRm(ProtobufModel):
    fd: int
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        fd: int = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class RegisterWasmExtensionReq(ProtobufModel):
    name: str
    wasm_gz: bytes
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        name: str = ...,
        wasm_gz: bytes = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class RegisterWasmExtension(ProtobufModel):
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class DeregisterWasmExtensionReq(ProtobufModel):
    name: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        name: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class ListWasmExtensionsReq(ProtobufModel):
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class ListWasmExtensions(ProtobufModel):
    names: list[str]
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        names: list[str] = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ExecWasmExtensionReq(ProtobufModel):
    name: str
    args: list[str]
    interactive: bool
    mem_fs: dict[str, bytes]
    tunnel_id: int
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        name: str = ...,
        args: list[str] = ...,
        interactive: bool = ...,
        mem_fs: dict[str, bytes] = ...,
        tunnel_id: int = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class ExecWasmExtension(ProtobufModel):
    stdout: bytes
    stderr: bytes
    exit_code: int
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        stdout: bytes = ...,
        stderr: bytes = ...,
        exit_code: int = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ServicesReq(ProtobufModel):
    hostname: str
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        hostname: str = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class ServiceDetailReq(ProtobufModel):
    service_info: ServiceInfoReq | None
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        service_info: ServiceInfoReq | None = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

class ServiceDetails(ProtobufModel):
    name: str
    display_name: str
    description: str
    status: int
    startup_type: int
    bin_path: str
    account: str
    def __init__(
        self,
        *,
        name: str = ...,
        display_name: str = ...,
        description: str = ...,
        status: int = ...,
        startup_type: int = ...,
        bin_path: str = ...,
        account: str = ...,
    ) -> None: ...

class Services(ProtobufModel):
    details: list[ServiceDetails]
    error: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        details: list[ServiceDetails] = ...,
        error: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class ServiceDetail(ProtobufModel):
    detail: ServiceDetails | None
    message: str
    response: commonpb.Response | None
    def __init__(
        self,
        *,
        detail: ServiceDetails | None = ...,
        message: str = ...,
        response: commonpb.Response | None = ...,
    ) -> None: ...

class StartServiceByNameReq(ProtobufModel):
    service_info: ServiceInfoReq | None
    request: commonpb.Request | None
    def __init__(
        self,
        *,
        service_info: ServiceInfoReq | None = ...,
        request: commonpb.Request | None = ...,
    ) -> None: ...

__all__ = [
    "BeaconRegister",
    "BeaconTasks",
    "CallExtension",
    "CallExtensionReq",
    "CdReq",
    "Chmod",
    "ChmodReq",
    "Chown",
    "ChownReq",
    "Chtimes",
    "ChtimesReq",
    "CloseSession",
    "Cp",
    "CpReq",
    "CurrentTokenOwner",
    "CurrentTokenOwnerReq",
    "DeregisterWasmExtensionReq",
    "Download",
    "DownloadReq",
    "EnvInfo",
    "EnvReq",
    "Envelope",
    "ExecWasmExtension",
    "ExecWasmExtensionReq",
    "Execute",
    "ExecuteAssembly",
    "ExecuteAssemblyReq",
    "ExecuteChild",
    "ExecuteChildren",
    "ExecuteChildrenReq",
    "ExecuteReq",
    "ExecuteWindowsReq",
    "FileInfo",
    "GetPrivs",
    "GetPrivsReq",
    "GetSystem",
    "Grep",
    "GrepLinePosition",
    "GrepReq",
    "GrepResult",
    "GrepResultsForFile",
    "HTTPSessionInit",
    "Ifconfig",
    "IfconfigReq",
    "Impersonate",
    "ImpersonateReq",
    "ImplantCapability",
    "InvokeExecuteAssemblyReq",
    "InvokeGetSystemReq",
    "InvokeInProcExecuteAssemblyReq",
    "InvokeMigrateReq",
    "InvokeSpawnDllReq",
    "KillReq",
    "ListExtensions",
    "ListExtensionsReq",
    "ListWasmExtensions",
    "ListWasmExtensionsReq",
    "Ls",
    "LsReq",
    "MakeToken",
    "MakeTokenReq",
    "MemfilesAdd",
    "MemfilesAddReq",
    "MemfilesListReq",
    "MemfilesRm",
    "MemfilesRmReq",
    "Migrate",
    "Mkdir",
    "MkdirReq",
    "Mount",
    "MountInfo",
    "MountReq",
    "Mv",
    "MvReq",
    "NetConnPivot",
    "NetInterface",
    "Netstat",
    "NetstatReq",
    "OpenSession",
    "PeerFailureType",
    "Ping",
    "PivotHello",
    "PivotListener",
    "PivotListeners",
    "PivotListenersReq",
    "PivotPeer",
    "PivotPeerEnvelope",
    "PivotPeerFailure",
    "PivotPing",
    "PivotServerKeyExchange",
    "PivotStartListenerReq",
    "PivotStopListenerReq",
    "PivotType",
    "PollInterval",
    "PollIntervalReq",
    "Portfwd",
    "PortfwdReq",
    "ProcessDump",
    "ProcessDumpReq",
    "Ps",
    "PsReq",
    "Pwd",
    "PwdReq",
    "RPortfwd",
    "RPortfwdReq",
    "Reconfigure",
    "ReconfigureReq",
    "Register",
    "RegisterExtension",
    "RegisterExtensionReq",
    "RegisterWasmExtension",
    "RegisterWasmExtensionReq",
    "RegistryCreateKey",
    "RegistryCreateKeyReq",
    "RegistryDeleteKey",
    "RegistryDeleteKeyReq",
    "RegistryListValuesReq",
    "RegistryRead",
    "RegistryReadHive",
    "RegistryReadHiveReq",
    "RegistryReadReq",
    "RegistrySubKeyList",
    "RegistrySubKeyListReq",
    "RegistryType",
    "RegistryValuesList",
    "RegistryWrite",
    "RegistryWriteReq",
    "RemoveServiceReq",
    "RevToSelf",
    "RevToSelfReq",
    "Rm",
    "RmReq",
    "RportFwdListener",
    "RportFwdListeners",
    "RportFwdListenersReq",
    "RportFwdStartListenerReq",
    "RportFwdStopListenerReq",
    "RunAs",
    "RunAsReq",
    "SSHCommand",
    "SSHCommandReq",
    "Screenshot",
    "ScreenshotReq",
    "ServiceDetail",
    "ServiceDetailReq",
    "ServiceDetails",
    "ServiceInfo",
    "ServiceInfoReq",
    "Services",
    "ServicesReq",
    "SessionRegister",
    "SetEnv",
    "SetEnvReq",
    "Shell",
    "ShellReq",
    "ShellResizeReq",
    "Sideload",
    "SideloadReq",
    "SockTabEntry",
    "Socks",
    "SocksData",
    "SpawnDll",
    "SpawnDllReq",
    "StartServiceByNameReq",
    "StartServiceReq",
    "StopServiceReq",
    "Task",
    "TaskReq",
    "Terminate",
    "TerminateReq",
    "Tunnel",
    "TunnelData",
    "UnsetEnv",
    "UnsetEnvReq",
    "Upload",
    "UploadReq",
    "WGPortForward",
    "WGPortForwardStartReq",
    "WGPortForwardStopReq",
    "WGSocks",
    "WGSocksServer",
    "WGSocksServers",
    "WGSocksServersReq",
    "WGSocksStartReq",
    "WGSocksStopReq",
    "WGTCPForwarder",
    "WGTCPForwarders",
    "WGTCPForwardersReq",
    "WindowsPrivilegeEntry",
]
